import json

S3_CS_DEPTH = [
    {"text": "Q: Explain IEEE 754 floating point representation. A: Single precision (32-bit): 1 sign bit + 8 exponent bits (bias 127) + 23 mantissa bits. Value = (-1)^s × 1.mantissa × 2^(exponent-127). Special values: exponent=0, mantissa=0 → ±0; exponent=255, mantissa=0 → ±∞; exponent=255, mantissa≠0 → NaN. Denormalized numbers (exponent=0, mantissa≠0): value = (-1)^s × 0.mantissa × 2^(-126). This is why 0.1 + 0.2 ≠ 0.3 in most languages."},
    {"text": "Q: Explain integer overflow and two's complement. A: Two's complement: negative -x is represented as 2^n - x. Range for n bits: -2^(n-1) to 2^(n-1)-1. Overflow: INT_MAX + 1 wraps to INT_MIN (undefined behavior in C, defined in Java). Example: 127 + 1 = -128 for 8-bit signed. Detection: overflow occurred if (a > 0 && b > 0 && sum < 0) || (a < 0 && b < 0 && sum > 0). Unsigned overflow wraps modulo 2^n (defined behavior in C)."},
    {"text": "Q: Explain bit manipulation techniques. A: Set bit n: x | (1<<n). Clear bit n: x & ~(1<<n). Toggle bit n: x ^ (1<<n). Check bit n: (x >> n) & 1. Lowest set bit: x & (-x) (two's complement trick). Count set bits: bin(x).count('1') or Brian Kernighan's: while x: x &= x-1; count += 1. Swap without temp: a ^= b; b ^= a; a ^= b. These are fundamental for systems programming and embedded development."},
    {"text": "Q: Explain endianness. A: Big-endian: most significant byte at lowest address (network byte order). Little-endian: least significant byte at lowest address (x86, ARM default). Example: 0x01020304 stored at address 0. Big-endian: [01,02,03,04]. Little-endian: [04,03,02,01]. Network protocols use big-endian. x86 uses little-endian. Conversion: htonl/ntohl (host to network long). Detection: int x=1; if(*(char*)&x == 1) little-endian. ARM can be either (bi-endian)."},
    {"text": "Q: Explain x86-64 calling convention and stack frame. A: System V AMD64 ABI: first 6 integer args in RDI, RSI, RDX, RCX, R8, R9; return value in RAX. Stack frame: pushed args → return address → saved RBP → local variables. RSP points to top of stack. Function prologue: push rbp; mov rbp, rsp; sub rsp, N. Epilogue: mov rsp, rbp; pop rbp; ret. Red zone: 128 bytes below RSP that signal handlers won't overwrite (leaf functions can use without adjusting RSP)."},
    {"text": "Q: Explain buffer overflow attacks and defenses. A: Stack buffer overflow: write past array bounds, overwriting return address to redirect execution. Attack: inject shellcode + overwrite return address to point to it. Defenses: (1) Stack canary: random value before return address, checked before ret. (2) NX bit: mark stack non-executable. (3) ASLR: randomize stack/libc addresses. (4) PIE: position-independent executable. (5) RELRO: mark GOT read-only. Modern: all combined, very hard to exploit."},
    {"text": "Q: Explain the relationship between C code and assembly. A: C: int sum(int a, int b) { return a + b; }. Assembly: sum: lea eax, [rdi+rsi]; ret. C: if(x > 0) y = 1; else y = -1;. Assembly: cmp rdi, 0; jg .L2; mov eax, -1; jmp .L3; .L2: mov eax, 1; .L3: ret. Loops become conditional jumps. Arrays become base + offset. Structs become contiguous memory. Pointers become registers holding addresses. Compiler optimizes: constant folding, dead code elimination, register allocation."},
    {"text": "Q: Explain pipeline hazards in processor design. A: Three types: (1) Data hazard: instruction depends on result of prior instruction still in pipeline. Fix: forwarding/bypassing (route result directly), pipeline stall (bubble). (2) Control hazard: branch changes PC, wrong instructions fetched. Fix: branch prediction (static/dynamic), delayed branch. (3) Structural hazard: two instructions need same hardware resource. Fix: duplicate resources, stall. Modern CPUs: out-of-order execution, speculative execution minimize stalls. Spectre/Meltdown exploit speculative execution side effects."},
    {"text": "Q: Explain branch prediction and its performance impact. A: Branch predictor guesses which way a branch goes before condition is evaluated. Static: always not-taken, or based on direction (backward = taken). Dynamic: 1-bit (remember last outcome), 2-bit saturating counter (need 2 mispredictions to change), two-level adaptive (history-based). Misprediction penalty: 15-20 cycles on modern CPUs. Code optimization: arrange code so common case is fall-through; use __builtin_expect; replace branches with conditional moves (cmov)."},
    {"text": "Q: Explain the Y86-64 instruction set. A: Y86-64: simplified x86-64 for teaching. Registers: RAX-RRSP (same 15 as x86-64). Instructions: halt, nop, rrmovl, irmovl, rmmovl, mrmovl, OPq (addq, subq, andq, xorq), jXX, cmovXX, call, ret, pushq, popq. Encoding: 1-10 bytes, first byte = opcode + register specifiers. No variable-length encoding complexity of x86. SEQ (sequential) → PIPE (pipelined) implementation teaches forwarding, hazard detection, and pipeline control."},
    {"text": "Q: Explain cache mapping: direct-mapped, set-associative, fully associative. A: Direct-mapped: each memory block maps to exactly one cache line (index = block_addr % num_lines). Fast but conflict misses. Fully associative: any block can go in any line. No conflict misses but expensive search. Set-associative: N-way compromise — each block maps to one set of N lines. Intel L1: 8-way, L2: 8-way, L3: 16-way. Replacement: LRU, pseudo-LRU, random. Cache line typically 64 bytes. Total size = lines × associativity × line_size."},
    {"text": "Q: How to write cache-friendly code? A: (1) Spatial locality: access data sequentially (row-major for C arrays). (2) Temporal locality: reuse data while in cache. (3) Blocking/tiling: process data in cache-sized chunks. Example: matrix multiply O(n³) — naive: thrashes cache. Blocked: process in B×B tiles fitting in cache, 2-10× faster. (4) Data structure layout: AOS → SOA (struct of arrays). (5) Avoid pointer chasing (linked lists → arrays). (6) Prefetching: __builtin_prefetch. Cache miss = 100-300 cycles vs 4 cycles for hit."},
    {"text": "Q: Explain virtual address translation with multi-level page tables. A: 64-bit virtual address: [unused | PML4 index (9) | PDPT index (9) | PD index (9) | PT index (9) | offset (12)]. CR3 register → PML4 table → PDPT → PD → PT → physical page + offset. 4-level walk = 4 memory accesses per translation (without TLB). Each table entry: P(present), R/W, U/S, accessed/dirty bits, physical frame number. TLB caches translations: typical 64-512 entries, >99% hit rate. Huge pages (2MB/1GB) skip last level(s)."},
    {"text": "Q: Explain TLB and its role in address translation. A: TLB (Translation Lookaside Buffer): hardware cache mapping virtual→physical page numbers. On each memory access: virtual page number → TLB lookup → hit: get physical frame, combine with offset → physical address. Miss: page table walk (hardware on x86, software on MIPS), then update TLB. TLB shootdown: when OS changes page table, must invalidate TLB entries on all CPUs (IPI). Context switch: flush TLB or use ASID (Address Space ID) to tag entries. TLB typically fully associative or highly set-associative."},
    {"text": "Q: How does malloc() work internally? A: malloc manages heap via free list of blocks. Each block: header (size + allocated flag) + payload + possible padding. Strategies: (1) Implicit free list: scan all blocks, O(n). (2) Explicit free list: doubly-linked free blocks, O(free blocks). (3) Segregated free lists: bins by size class (ptmalloc/glibc approach). Placement: first-fit, next-fit, best-fit. Splitting: if block much larger than request, split. Coalescing: merge adjacent free blocks (immediate or deferred). Boundary tags enable backward coalescing."},
    {"text": "Q: What is the difference between malloc, calloc, and realloc? A: malloc(size): allocates size bytes, uninitialized (contains garbage). calloc(nmemb, size): allocates nmemb×size bytes, zero-initialized. realloc(ptr, new_size): resize previously allocated block — may move to new location (old data copied), returns new pointer. If new_size < old: may split block. If ptr=NULL: equivalent to malloc. Common errors: not checking NULL return, double free, use after free, memory leak (forgetting to free). free(NULL) is safe (no-op)."},
    {"text": "Q: Explain garbage collection algorithms. A: (1) Mark-and-sweep: from roots (stack, globals), mark reachable objects; sweep unmarked. Pause time proportional to heap size. (2) Copying: divide heap into from/to spaces; copy reachable objects from→to, compacting. Good locality, no fragmentation, but uses 2× memory. (3) Generational: new objects in young generation, frequent minor GC; survivors promoted to old generation, rare major GC. Based on weak generational hypothesis: most objects die young. (4) Reference counting: increment/decrement on assign, free when zero. Can't handle cycles."},
    {"text": "Q: Explain common memory errors and how to detect them. A: (1) Buffer overflow: write past allocated bounds. Valgrind/ASan detect. (2) Use after free: access freed memory. ASan quarantines freed blocks. (3) Double free: free same block twice, corrupts free list. (4) Memory leak: never freed, grows over time. Valgrind --leak-check=full. (5) Uninitialized read: use memory before writing. Valgrind/MemorySanitizer. (6) Stack buffer overflow: overwrite return address. Stack canary protects. Tools: Valgrind (slow, 20×), AddressSanitizer (2×, compile-time), UndefinedBehaviorSanitizer."},
    {"text": "Q: Explain thread safety and synchronization primitives. A: Thread safety: code works correctly with concurrent access. Primitives: (1) Mutex: exclusive lock, one thread at a time. (2) Semaphore: counter with wait/signal, generalizes mutex. (3) Condition variable: wait for condition, signal/broadcast on change. (4) Read-write lock: multiple readers OR one writer. (5) Spinlock: busy-wait lock (for short critical sections). Rules: always lock before shared data access; keep critical sections short; avoid deadlock by consistent lock ordering; never hold lock during I/O."},
    {"text": "Q: Explain the producer-consumer problem. A: Bounded buffer shared between producer (adds items) and consumer (removes). Solution: semaphore empty = N (empty slots), semaphore full = 0 (filled slots), mutex = 1. Producer: wait(empty); wait(mutex); add_item(); signal(mutex); signal(full). Consumer: wait(full); wait(mutex); remove_item(); signal(mutex); signal(empty). Key: empty/full control flow, mutex protects buffer. Without empty semaphore: producer overflows. Without full: consumer reads empty buffer."},
    {"text": "Q: Explain the readers-writers problem. A: Multiple readers can read simultaneously, but writers need exclusive access. First solution (readers priority): readers can starve writers. Counter readcount with mutex; wrt semaphore for writers. Reader: wait(mutex); readcount++; if readcount==1: wait(wrt); signal(mutex); // read; wait(mutex); readcount--; if readcount==0: signal(wrt); signal(mutex). Writer: wait(wrt); // write; signal(wrt). Fair solution: use a turnstile semaphore so writers aren't starved."},
    {"text": "Q: Explain Socket API for network programming. A: Server: sockfd = socket(AF_INET, SOCK_STREAM, 0); bind(sockfd, &addr, sizeof(addr)); listen(sockfd, backlog); connfd = accept(sockfd, &client_addr, &len); read(connfd, buf, n); write(connfd, buf, n); close(connfd). Client: sockfd = socket(...); connect(sockfd, &server_addr, sizeof(...)); write(sockfd, ...); read(sockfd, ...); close(sockfd). Key: TCP is byte-stream (no message boundaries), must handle partial reads. Use select/poll/epoll for multiple connections."},
    {"text": "Q: Explain concurrent server designs. A: (1) Process per connection: fork() after accept. Simple but expensive (8KB+ per process). (2) Thread per connection: pthread_create. Lighter but still O(n) threads. (3) Thread pool: pre-create N threads, dispatch via queue. Avoids thread creation overhead. (4) Event-driven: single thread, select/poll/epoll, non-blocking I/O. Best scalability (Nginx, Redis). (5) Hybrid: event-driven accept + thread pool for compute. C10K problem: 10K concurrent connections requires event-driven or async I/O."},
    {"text": "Q: Explain I/O multiplexing: select, poll, epoll. A: select(nfds, readfds, writefds, exceptfds, timeout): checks up to FD_SETSIZE (1024) file descriptors. O(n) scan. poll(fds, nfds, timeout): array of {fd, events, revents}, no 1024 limit but still O(n). epoll (Linux): epoll_create → epoll_ctl(add/modify) → epoll_wait. O(1) for ready events, O(active) not O(total). Edge-triggered vs level-triggered: ET notifies once per new event (must drain all data), LT notifies while data available. Nginx uses epoll+ET. kqueue (BSD/macOS) is epoll equivalent."},
    {"text": "Q: Explain CUDA programming model: grids, blocks, threads. A: Kernel launched as grid of blocks, each block contains threads. Hierarchy: grid → block → thread. Block dimensions: up to 1024 threads (e.g., 32×32). Grid dimensions: up to 2^31-1 blocks. Each thread has unique ID: threadIdx + blockIdx × blockDim. Memory: global (all threads, slow), shared (per block, fast, 48KB), local (per thread, in registers), constant (read-only, cached). Warps: 32 threads execute in lockstep (SIMT). Divergence within warp causes serialization. Kernel launch: kernel<<<numBlocks, threadsPerBlock>>>(args)."},
    {"text": "Q: Explain GPU memory hierarchy and optimization. A: GPU memory (fastest to slowest): registers (per thread, ~1 cycle) → shared memory (per block, ~5 cycles, bank conflicts possible) → L1 cache (per SM, ~30 cycles) → L2 cache (global, ~100 cycles) → global memory (HBM, ~400 cycles) → host memory (PCIe transfer, ~10000 cycles). Optimization: coalesced memory access (consecutive threads access consecutive addresses), shared memory tiling (load tile, compute, store), minimize host-device transfers, use streams for overlap. Occupancy: enough warps per SM to hide latency."},
    {"text": "Q: Explain MapReduce programming model. A: Map: process input (key, value) pairs, emit intermediate (k2, v2). Shuffle: group by k2. Reduce: process all values for each k2, emit (k2, result). Example word count: Map(docid, text) → emit(word, 1) for each word. Reduce(word, [1,1,1,...]) → emit(word, count). Fault tolerance: if a worker fails, reassign its tasks. Data locality: schedule map tasks where data resides. Combiner: local reduce on map output to reduce shuffle traffic. Used by Hadoop, Spark (in-memory optimization)."},
    {"text": "Q: Explain data parallelism vs task parallelism. A: Data parallelism: same operation on different data elements simultaneously (SIMD/GPU). Example: add two arrays element-wise. Scales with data size. Task parallelism: different operations on different data simultaneously (different functions on different cores). Example: one thread handles network I/O, another computes, another renders. In practice: hybrid — data parallel within tasks (GPU), task parallel across pipeline stages (CPU). Amdahl's law limits speedup by serial fraction. Gustafson's law: speedup scales with problem size."},
    {"text": "Q: Explain ELF format and the linking process. A: ELF (Executable and Linkable Format): header (magic, type, architecture) + sections. Key sections: .text (code), .data (initialized globals), .bss (uninitialized, zero-filled), .rodata (constants), .symtab (symbol table), .rel.text/.rel.data (relocation entries). Linking: (1) Symbol resolution: match references to definitions across object files. (2) Relocation: modify code/data to reflect actual addresses. Static linking: copies library code into executable. Dynamic linking: at runtime, ld.so loads shared libraries and resolves symbols via GOT/PLT."},
    {"text": "Q: Explain static vs dynamic linking. A: Static linking: linker copies all library code into executable. Pros: self-contained, no dependencies. Cons: large binary, library updates require recompilation. Dynamic linking: executable references shared library (.so/.dll), loaded at runtime by dynamic linker (ld.so). Pros: small binary, library updates without recompilation, shared memory (one .so in memory for all processes). Cons: dependency management, version conflicts (DLL hell), slight startup overhead. ldd shows dependencies. LD_PRELOAD can override functions (library interposition)."},
    {"text": "Q: Explain PIC (Position-Independent Code) and library interposition. A: PIC: code that works regardless of load address. Uses PC-relative addressing and GOT (Global Offset Table) for global variables and functions. GOT entry filled by dynamic linker at load time. PLT (Procedure Linkage Table): lazy binding — first call resolves symbol address, subsequent calls use cached GOT entry. Library interposition: (1) LD_PRELOAD: load your .so before real library, override functions. (2) Link-time: --wrap flag. (3) Compile-time: #define malloc my_malloc. Used for profiling, debugging, mocking."},
    {"text": "Q: Explain Unix signals and signal handling. A: Signal: asynchronous notification to process. Common: SIGINT (Ctrl+C), SIGSEGV (segfault), SIGKILL (uncatchable termination), SIGTERM (graceful termination), SIGCHLD (child exited), SIGALRM (timer). Handling: signal(SIGINT, handler) or sigaction (preferred, more portable). Handler restrictions: can only call async-signal-safe functions (write, _exit, not printf/malloc). Pending signals of same type may be coalesced (not queued). Real-time signals (SIGRTMIN-SIGRTMAX) are queued. Common bug: handler accesses shared variable without volatile sig_atomic_t."},
    {"text": "Q: Explain how a shell works. A: Shell loop: (1) Print prompt. (2) Read command line. (3) Parse: tokenize, handle pipes, redirects, background (&). (4) Execute: fork() child process; child: set up redirections (dup2), execvp(command, args); parent: waitpid (foreground) or add to job list (background). Pipes: pipe(fds); fork; child1: dup2(fds[1], STDOUT); close(fds[0]); exec cmd1; child2: dup2(fds[0], STDIN); close(fds[1]); exec cmd2. Signal handling: SIGINT kills foreground child, not shell. SIGCHLD: reap zombie processes (waitpid with WNOHANG)."},
    {"text": "Q: Explain inter-process communication (IPC) mechanisms. A: (1) Pipes: unidirectional, parent-child only. (2) Named pipes (FIFO): filesystem-based, unrelated processes. (3) Shared memory: fastest IPC, mmap or shmget. Needs synchronization (semaphores). (4) Message queues: kernel-managed message lists, msgget/msgsnd/msgrcv. (5) Sockets: network-capable, bidirectional. (6) Signals: lightweight, limited information. (7) Unix domain sockets: local only, faster than TCP. Choice: shared memory for throughput, sockets for simplicity and network transparency, pipes for simple parent-child."},
]

out = {"data": [{"text": t["text"], "level": "3"} for t in S3_CS_DEPTH]}
with open(r"d:\VORTEX_FLAME\soul_training_data\cezanne\cezanne_s3_cs_depth_v2.json", "w", encoding="utf-8") as f:
    json.dump(out, f, ensure_ascii=False, indent=2)
print(f"S3: {len(S3_CS_DEPTH)} items saved")
