import json

S2_LOGIC_DEBUG = [
    {"text": "Q: Find the bug: def binary_search(arr, target): left, right = 0, len(arr); while left < right: mid = (left + right) // 2; if arr[mid] == target: return mid; elif arr[mid] < target: left = mid; else: right = mid; return -1. A: Two bugs: (1) off-by-one: when arr[mid] < target, should be left = mid + 1, not left = mid (causes infinite loop when left = mid). (2) Same issue: when arr[mid] > target, should be right = mid, which is correct here. The key insight: left = mid can stall when mid equals left (happens when left+1 == right), creating an infinite loop."},
    {"text": "Q: Find the bug: def remove_duplicates(lst): for i in range(len(lst)): if lst[i] in lst[:i]: lst.pop(i); return lst. A: Modifying a list while iterating by index causes skipped elements. After lst.pop(i), element at index i+1 shifts to index i, but the loop increments i, skipping it. Fix: iterate backwards: for i in range(len(lst)-1, -1, -1), or build a new list: [x for i, x in enumerate(lst) if x not in lst[:i]]."},
    {"text": "Q: Find the bug: def flatten(nested): result = []; for item in nested: if isinstance(item, list): result += flatten(item); else: result.append(item); return result. A: This actually works for nested lists, but has a subtle issue with very deep nesting: Python's default recursion limit (~1000) will cause RecursionError. Fix: use iterative approach with explicit stack, or set sys.setrecursionlimit(). Also, strings will cause infinite recursion since a character of a string is still a string."},
    {"text": "Q: Find the bug: class Counter: count = 0; def increment(self): self.count += 1; return self.count. A: 'count' is a class variable shared across all instances. If c1 = Counter() and c2 = Counter(), c1.increment() affects c2.count too. Fix: make count an instance variable by defining it in __init__: def __init__(self): self.count = 0. Class variables are for shared state, instance variables for per-object state."},
    {"text": "Q: Find the bug: import threading; counter = 0; def increment(): global counter; for _ in range(100000): counter += 1; t1 = threading.Thread(target=increment); t2 = threading.Thread(target=increment); t1.start(); t2.start(); t1.join(); t2.join(); print(counter). A: Race condition. counter += 1 is not atomic: it reads, increments, and writes. Two threads can read the same value before either writes. Expected: 200000, actual: unpredictable (< 200000). Fix: use threading.Lock() around the increment, or use atomic operations."},
    {"text": "Q: Find the bug: def merge_sort(arr): if len(arr) <= 1: return arr; mid = len(arr) // 2; left = merge_sort(arr[:mid]); right = merge_sort(arr[mid:]); return merge(left, right). A: This is actually correct! But there's a performance issue: arr[:mid] and arr[mid:] create copies at every level, using O(n log n) total memory instead of O(n). Fix: pass indices and use a single auxiliary array. Also, for small subarrays (< 10 elements), insertion sort is faster due to lower overhead."},
    {"text": "Q: Find the bug: try: f = open('data.txt'); data = f.read(); process(data). A: Missing finally/close. If process() raises an exception, the file handle leaks. Fix: use context manager: with open('data.txt') as f: data = f.read(); process(data). The 'with' statement guarantees f.close() is called even if an exception occurs."},
    {"text": "Q: Find the bug: def cache(func): results = {}; def wrapper(*args): if args not in results: results[args] = func(*args); return results[args]; return wrapper. A: Using mutable default arguments or unhashable args will fail. If func takes a list argument, args will contain an unhashable type, causing TypeError. Fix: convert args to a hashable representation, or use functools.lru_cache which handles this. Also, the cache grows unboundedly — no eviction policy."},
    {"text": "Q: Prove using formal logic: if P→Q and Q→R, then P→R (hypothetical syllogism). A: Assume P. Since P→Q (given), by modus ponens, Q follows. Since Q→R (given), by modus ponens again, R follows. Therefore P→R. Formally: {P→Q, Q→R} ⊢ P→R. This is the transitivity of implication, also known as chain reasoning."},
    {"text": "Q: Prove by contradiction: √2 is irrational. A: Assume √2 = p/q where p,q are coprime integers. Then 2 = p²/q², so p² = 2q². Thus p² is even, so p is even (if p were odd, p² would be odd). Write p = 2k. Then 4k² = 2q², so q² = 2k², meaning q² is even, so q is even. But p and q both even contradicts coprimality. Therefore √2 is irrational."},
    {"text": "Q: What is the contrapositive? Prove: if n² is even, then n is even. A: Contrapositive of P→Q is ¬Q→¬P, which is logically equivalent. Contrapositive: if n is odd, then n² is odd. Proof: n = 2k+1, then n² = 4k²+4k+1 = 2(2k²+2k)+1, which is odd. Since contrapositive is true, original statement is true. Contrapositive is often easier to prove than the original."},
    {"text": "Q: Explain proof by mathematical induction. A: Two steps: (1) Base case: prove P(1) is true. (2) Inductive step: prove P(k)→P(k+1) for all k≥1. Then P(n) is true for all n≥1. Think of it as dominoes: if you knock the first one (base case), and each one knocks the next (inductive step), all fall. Strong induction: assume P(1),...,P(k) all true to prove P(k+1)."},
    {"text": "Q: Explain Hoare logic and prove {x > 0} x = x + 1 {x > 1}. A: Hoare triple {P} S {Q}: if precondition P holds before statement S, then postcondition Q holds after. Assignment rule: {P[x→e]} x = e {P}. For {x > 0} x = x + 1 {x > 1}: substitute x-1 for x in postcondition: x-1 > 1, i.e., x > 2... Wait, let me redo. Assignment axiom: {Q[x→e]} x=e {Q}. So {Q[x→x+1]} x=x+1 {Q}. We want Q = x>1. Pre: (x>1)[x→x+1] = x+1>1 = x>0. So {x>0} x=x+1 {x>1}. ✓"},
    {"text": "Q: What is the difference between ∀x P(x) and ∃x P(x)? Negate both. A: ∀x P(x): P holds for ALL x. ∃x P(x): P holds for SOME x. Negation: ¬(∀x P(x)) ≡ ∃x ¬P(x) (to disprove 'all', find one counterexample). ¬(∃x P(x)) ≡ ∀x ¬P(x) (to disprove 'exists', show none exist). Example: ¬(∀x, x>0) ≡ ∃x, x≤0."},
    {"text": "Q: Explain the pigeonhole principle with an example. A: If n items are placed into m containers and n > m, then at least one container has more than one item. Example: in any group of 13 people, at least 2 share a birth month (12 months, 13 people). Stronger form: if n items in m boxes, some box has at least ⌈n/m⌉ items."},
    {"text": "Q: Write Dijkstra's algorithm and explain why a priority queue is needed. A: def dijkstra(graph, start): dist = {v: float('inf') for v in graph}; dist[start] = 0; pq = [(0, start)]; visited = set(); while pq: d, u = heapq.heappop(pq); if u in visited: continue; visited.add(u); for v, w in graph[u]: if d + w < dist[v]: dist[v] = d + w; heapq.heappush(pq, (dist[v], v)); return dist. Priority queue gives O((V+E)logV) vs O(V²) without it. It always processes the closest unvisited node first, which is essential for correctness."},
    {"text": "Q: Implement BFS and DFS. When to use each? A: BFS (queue): from collections import deque; def bfs(graph, start): visited = {start}; q = deque([start]); while q: node = q.popleft(); for neighbor in graph[node]: if neighbor not in visited: visited.add(neighbor); q.append(neighbor). DFS (stack/recursion): def dfs(graph, node, visited=None): if visited is None: visited = set(); visited.add(node); for neighbor in graph[node]: if neighbor not in visited: dfs(graph, neighbor, visited). BFS finds shortest path in unweighted graphs. DFS is better for topological sort, cycle detection, and exploring all paths."},
    {"text": "Q: Explain topological sort. When is it possible? A: Topological sort orders vertices of a DAG such that for every edge u→v, u comes before v. Only possible on Directed Acyclic Graphs (DAGs). Algorithm: compute in-degrees, repeatedly remove nodes with in-degree 0. If not all nodes removed, graph has a cycle. Application: build systems (compile dependencies), course prerequisites, task scheduling."},
    {"text": "Q: Explain Kruskal's and Prim's algorithms for MST. A: Kruskal: sort edges by weight, add cheapest edge that doesn't create a cycle (use Union-Find). O(E log E). Prim: start from any node, always add cheapest edge connecting tree to non-tree node (use priority queue). O(E log V). Kruskal better for sparse graphs, Prim for dense graphs. Both produce minimum spanning tree for connected weighted undirected graphs."},
    {"text": "Q: Implement quicksort with Lomuto partition. Explain time complexity. A: def quicksort(arr, lo=0, hi=None): if hi is None: hi = len(arr)-1; if lo < hi: p = partition(arr, lo, hi); quicksort(arr, lo, p-1); quicksort(arr, p+1, hi). def partition(arr, lo, hi): pivot = arr[hi]; i = lo; for j in range(lo, hi): if arr[j] <= pivot: arr[i], arr[j] = arr[j], arr[i]; i += 1; arr[i], arr[hi] = arr[hi], arr[i]; return i. Average: O(n log n). Worst: O(n²) when already sorted. Randomized pivot avoids worst case in practice."},
    {"text": "Q: Implement merge sort and explain why it's stable. A: def mergesort(arr): if len(arr) <= 1: return arr; mid = len(arr)//2; left = mergesort(arr[:mid]); right = mergesort(arr[mid:]); return merge(left, right). def merge(a, b): result = []; i = j = 0; while i < len(a) and j < len(b): if a[i] <= b[j]: result.append(a[i]); i += 1; else: result.append(b[j]); j += 1; result.extend(a[i:]); result.extend(b[j:]); return result. Stable because a[i] <= b[j] preserves order of equal elements. Always O(n log n), but uses O(n) extra space."},
    {"text": "Q: Implement heap sort. A: def heapsort(arr): n = len(arr); [heapify(arr, n, i) for i in range(n//2-1, -1, -1)]; for i in range(n-1, 0, -1): arr[0], arr[i] = arr[i], arr[0]; heapify(arr, i, 0). def heapify(arr, n, i): largest = i; l, r = 2*i+1, 2*i+2; if l < n and arr[l] > arr[largest]: largest = l; if r < n and arr[r] > arr[largest]: largest = r; if largest != i: arr[i], arr[largest] = arr[largest], arr[i]; heapify(arr, n, largest). O(n log n) guaranteed, in-place, but not stable."},
    {"text": "Q: Implement a binary search tree with insert and search. A: class Node: def __init__(self, val): self.val = val; self.left = self.right = None. class BST: def __init__(self): self.root = None; def insert(self, val): self.root = self._insert(self.root, val); def _insert(self, node, val): if not node: return Node(val); if val < node.val: node.left = self._insert(node.left, val); elif val > node.val: node.right = self._insert(node.right, val); return node; def search(self, val): return self._search(self.root, val); def _search(self, node, val): if not node or node.val == val: return node; if val < node.val: return self._search(node.left, val); return self._search(node.right, val). Average O(log n), worst O(n) if unbalanced."},
    {"text": "Q: Explain the 0/1 knapsack problem with DP solution. A: Given items with weight w[i] and value v[i], and capacity W, maximize total value without exceeding capacity. DP: dp[i][j] = max value using first i items with capacity j. Recurrence: dp[i][j] = max(dp[i-1][j], dp[i-1][j-w[i]] + v[i]) if j >= w[i], else dp[i-1][j]. Base: dp[0][j] = 0. Space optimization: use 1D array, iterate j from W down to w[i]. Time: O(nW), pseudo-polynomial."},
    {"text": "Q: Explain SQL injection and how to prevent it. A: SQL injection: attacker inserts SQL code into input fields. Example: query = 'SELECT * FROM users WHERE name=' + user_input. If user_input = \"' OR '1'='1\", query becomes: SELECT * FROM users WHERE name='' OR '1'='1' — returns all rows. Prevention: (1) Parameterized queries: cursor.execute('SELECT * FROM users WHERE name=?', (user_input,)). (2) Input validation/sanitization. (3) Least privilege database accounts. (4) ORM frameworks."},
    {"text": "Q: Explain virtual memory, page tables, and TLB. A: Virtual memory gives each process illusion of contiguous address space. Page table maps virtual pages to physical frames. On memory access: CPU generates virtual address → MMU checks TLB (Translation Lookaside Buffer, hardware cache of recent translations) → TLB hit: direct physical address; TLB miss: walk page table in memory → page fault if not in physical memory → OS loads from disk. TLB typically has 64-512 entries, >99% hit rate, reduces address translation from 2+ memory accesses to 1."},
    {"text": "Q: Explain TCP congestion control: slow start, congestion avoidance, fast recovery. A: Slow start: cwnd starts at 1 MSS, doubles each RTT (exponential growth) until cwnd reaches ssthresh. Congestion avoidance: cwnd increases by 1 MSS per RTT (linear growth). On 3 duplicate ACKs (mild congestion): fast retransmit + fast recovery: ssthresh = cwnd/2, cwnd = ssthresh + 3 MSS, retransmit lost segment. On timeout (severe congestion): ssthresh = cwnd/2, cwnd = 1 MSS, slow start again. This is TCP Reno."},
    {"text": "Q: Explain the four necessary conditions for deadlock. How to prevent each? A: (1) Mutual exclusion: resources can't be shared. Prevention: allow shared access where possible. (2) Hold and wait: process holds resources while waiting for others. Prevention: request all resources at once. (3) No preemption: resources can't be forcibly taken. Prevention: allow preemption, rollback. (4) Circular wait: circular chain of processes. Prevention: impose total ordering on resources, always request in order. All four must hold simultaneously for deadlock."},
    {"text": "Q: Explain compiler phases: lexing, parsing, semantic analysis, code generation. A: (1) Lexing: source code → tokens (keywords, identifiers, operators). (2) Parsing: tokens → AST (abstract syntax tree) based on grammar rules. (3) Semantic analysis: type checking, symbol resolution, scope rules on AST. (4) Intermediate code generation: AST → IR (three-address code, SSA). (5) Optimization: constant folding, dead code elimination, loop optimization on IR. (6) Code generation: IR → target machine code. Each phase has a well-defined input/output interface."},
    {"text": "Q: Explain the difference between process and thread. A: Process: independent execution unit with own address space, file descriptors, heap. Thread: lightweight unit sharing address space within a process, but has own stack and registers. Creating a thread is faster (no address space copy). Context switch between threads is faster (same address space). Threads share heap (need synchronization), processes don't (IPC needed). Multi-process: safer (isolation), more overhead. Multi-thread: efficient sharing, but race conditions."},
    {"text": "Q: Explain Big-O notation with examples. A: f(n) = O(g(n)) if ∃c, n₀ such that f(n) ≤ c·g(n) for all n ≥ n₀. Examples: O(1) — hash lookup; O(log n) — binary search; O(n) — linear scan; O(n log n) — merge sort; O(n²) — bubble sort; O(2^n) — subset enumeration. Drop constants and lower-order terms: 3n² + 5n + 7 = O(n²). Space complexity follows same notation. Amortized analysis: occasional expensive operation averaged over many cheap ones (e.g., dynamic array resizing)."},
]

out = {"data": [{"text": t["text"], "level": "2"} for t in S2_LOGIC_DEBUG]}
with open(r"d:\VORTEX_FLAME\soul_training_data\cezanne\cezanne_s2_logic_debug_v2.json", "w", encoding="utf-8") as f:
    json.dump(out, f, ensure_ascii=False, indent=2)
print(f"S2: {len(S2_LOGIC_DEBUG)} items saved")
