#!/usr/bin/env python3
"""Generate S3 Computer Science training data for 7B Cezanne (from S2 base)
Covers: CSAPP + MIT 6.S081/6.006/6.824 + Stanford CS149 + Linux PFRA + PyTorch C++
Strategy: Keep math+logic (S1+S2), add CS depth as S3
"""
import json, os, sys
sys.stdout.reconfigure(encoding='utf-8', errors='replace')

OUT = r"D:\VORTEX_FLAME\soul_training_data\cezanne"

CS_DATA = [
    {"instruction": "Explain virtual memory and page tables. How does TLB speed up address translation?",
     "input": "", "output": "Virtual memory gives each process the illusion of having its own large, contiguous address space, even though physical RAM is limited and shared.\n\nHow it works:\n1. Virtual addresses are translated to physical addresses via page tables\n2. Memory is divided into fixed-size pages (typically 4KB)\n3. Each process has its own page table mapping virtual→physical pages\n4. A page table entry (PTE) contains: physical frame number, valid bit, dirty bit, access bits\n\nTLB (Translation Lookaside Buffer):\nThe TLB is a hardware cache inside the CPU that stores recent virtual→physical translations. Without TLB, every memory access requires a page table walk (reading from RAM), which is extremely slow.\n\nAddress translation with TLB:\n1. CPU generates virtual address\n2. TLB is checked first (hardware, ~1 cycle)\n3. TLB hit: physical address returned immediately\n4. TLB miss: page table walk in memory (~100 cycles), then result cached in TLB\n\nTLB typically has 64-1536 entries with >95% hit rate, making virtual memory practical."},

    {"instruction": "Explain the difference between a process and a thread. When would you use each?",
     "input": "", "output": "Process vs Thread:\n\nProcess:\n- Independent execution unit with its own address space\n- Has its own: virtual memory, file descriptors, signal handlers\n- Created by fork() (Unix) or CreateProcess() (Windows)\n- Context switch is expensive (must swap page tables, flush TLB)\n- Communication requires IPC (pipes, shared memory, sockets)\n\nThread:\n- Lightweight execution unit within a process\n- Shares: address space, file descriptors, heap\n- Has its own: stack, registers, program counter\n- Created by pthread_create() (POSIX) or std::thread (C++)\n- Context switch is cheap (no page table swap)\n- Communication via shared memory (fast but needs synchronization)\n\nWhen to use processes:\n- Need isolation (one crash shouldn't kill others)\n- Security boundaries (different permissions)\n- Running external programs\n\nWhen to use threads:\n- Need shared state (parallel processing on same data)\n- Performance (cheap context switches)\n- Real-time responsiveness (UI thread + worker threads)"},

    {"instruction": "Explain the CPU pipeline and why branch prediction matters for performance.",
     "input": "", "output": "CPU Pipeline:\nModern CPUs execute instructions in stages (typically 5-15 stages):\n1. Fetch: Load instruction from memory\n2. Decode: Determine what the instruction does\n3. Execute: Perform the operation (ALU)\n4. Memory: Access data memory if needed\n5. Writeback: Store result to register\n\nPipelining allows overlapping: while instruction 2 is decoding, instruction 1 is executing, and instruction 3 is being fetched. This gives throughput of ~1 instruction per cycle (ideally).\n\nBranch Prediction:\nWhen the CPU encounters a conditional branch (if/else), it doesn't know which path to take until the branch resolves (several cycles later). Instead of stalling, the CPU predicts the outcome and speculatively executes the predicted path.\n\nIf prediction is correct: no penalty, full speed\nIf prediction is wrong (branch misprediction): must flush the pipeline and restart → penalty of 15-20 cycles on modern CPUs\n\nBranch prediction accuracy: ~95-99% using:\n- Static prediction: always predict not-taken (simple)\n- Dynamic prediction: 2-bit saturating counters, tournament predictors\n- Modern: neural-inspired perceptron predictors, TAGE\n\nThis is why 'if' statements in hot loops can be expensive — mispredictions kill performance."},

    {"instruction": "Explain how the stack works in C programs. What is a stack overflow?",
     "input": "", "output": "The Stack in C:\n\nThe stack is a region of memory that grows downward (from high to low addresses) and manages:\n1. Function call frames (activation records)\n2. Local variables\n3. Return addresses\n4. Function parameters\n\nStack frame layout (x86-64):\n┌──────────────────┐  High address\n│  Return address   │\n│  Saved RBP        │\n│  Local var 1      │\n│  Local var 2      │\n│  ...              │\n└──────────────────┘  Low address (RSP)\n\nCall sequence:\n1. CALL instruction pushes return address onto stack\n2. Function prologue: push RBP, mov RBP,RSP, allocate locals\n3. Function executes\n4. Function epilogue: mov RSP,RBP, pop RBP, RET pops return address\n\nStack Overflow:\nOccurs when the stack grows beyond its allocated size (typically 8MB on Linux).\n\nCauses:\n1. Infinite recursion: each call adds a frame until stack is exhausted\n2. Very large local arrays: int arr[10000000] on stack\n3. Stack clash: stack grows into heap region\n\nPrevention:\n- Use iteration instead of deep recursion\n- Allocate large arrays on the heap (malloc)\n- Increase stack size: ulimit -s unlimited (temporary fix)\n- Compiler warnings: -Wframe-larger-than=N"},

    {"instruction": "Explain memory-mapped I/O and how it differs from port-mapped I/O.",
     "input": "", "output": "Memory-Mapped I/O (MMIO):\nDevice registers are mapped into the same address space as regular memory. CPU uses normal load/store instructions to access devices.\n\nExample: Writing to address 0x3F200000 (GPIO on Raspberry Pi) controls a hardware pin.\n\nmov [0x3F200000], 1  ; Set GPIO pin high\n\nPort-Mapped I/O (PMIO):\nDevice registers are in a separate I/O address space. CPU uses special IN/OUT instructions.\n\nExample: x86 I/O ports\n\nout 0x60, al  ; Send byte to keyboard controller\n\nKey differences:\n- MMIO: Same instructions as memory access (mov,ldr,str)\n- PMIO: Special instructions (in, out) and separate address space\n- MMIO: More flexible, can use all addressing modes\n- PMIO: Simpler hardware, smaller address space\n\nModern systems primarily use MMIO:\n- PCIe devices use MMIO (BAR - Base Address Register)\n- GPUs are entirely MMIO\n- ARM/RISC-V only support MMIO (no IN/OUT instructions)\n- x86 supports both for legacy compatibility\n\nIn Linux, device drivers use ioremap() to map physical MMIO addresses into kernel virtual address space."},

    {"instruction": "Explain the concept of a deadlock. What are the four necessary conditions? How to prevent it?",
     "input": "", "output": "Deadlock is a state where two or more processes are each waiting for a resource held by the other, and none can proceed.\n\nFour Necessary Conditions (Coffman conditions):\n1. Mutual Exclusion: At least one resource must be non-sharable (only one process can use it at a time)\n2. Hold and Wait: A process holds at least one resource and is waiting for additional resources held by others\n3. No Preemption: Resources cannot be forcibly taken away from a process\n4. Circular Wait: There exists a circular chain of processes, each waiting for a resource held by the next\n\nAll four must hold simultaneously for deadlock to occur.\n\nPrevention strategies (break one condition):\n1. Break Mutual Exclusion: Use sharable resources (e.g., read-only files)\n2. Break Hold and Wait: Request all resources at once before execution\n3. Break No Preemption: Allow resource preemption (rollback)\n4. Break Circular Wait: Impose a total ordering on resources; processes must request in increasing order\n\nDetection and Recovery:\n- Resource allocation graph (cycle = deadlock)\n- Banker's algorithm (safe state checking)\n- Timeout-based recovery\n- Kill victim process\n\nIn practice: Most OSes use the ostrich algorithm (ignore deadlocks, reboot if they happen) because prevention is too expensive."},

    {"instruction": "Explain how malloc() works internally. What is the difference between malloc, calloc, and realloc?",
     "input": "", "output": "How malloc() works internally:\n\n1. malloc(size) requests 'size' bytes from the heap\n2. The memory allocator (glibc ptmalloc2) manages free chunks using:\n   - Bins: arrays of linked lists for different size classes\n   - Fastbins: for small allocations (<160B), LIFO for speed\n   - Unsorted bin: recently freed chunks\n   - Large bins: sorted by size for best-fit allocation\n3. If no free chunk fits, malloc calls sbrk() or mmap() to get more memory from the OS\n4. Returns a pointer to the allocated memory (or NULL on failure)\n\nInternal structure:\nEach allocated block has a header containing: size, prev_size, flags (IS_MMAPPED, PREV_INUSE)\nThis is why malloc(0) still uses memory — the header takes space.\n\ndifferences:\n\nmalloc(n): Allocates n bytes, uninitialized (contains garbage)\np = malloc(100);  // May contain any data\n\ncalloc(n, size): Allocates n*size bytes, initialized to zero\np = calloc(10, 10);  // 100 bytes, all zeros\n// calloc also checks for overflow: n*size might overflow size_t\n\nrealloc(ptr, new_size): Resizes previously allocated memory\np = malloc(100);\np = realloc(p, 200);  // Expand to 200 bytes\n// If possible, extends in place. Otherwise, allocates new block, copies data, frees old.\n// If ptr is NULL, equivalent to malloc. If new_size is 0, equivalent to free.\n\nCommon bugs:\n- Memory leak: malloc without free\n- Double free: freeing same pointer twice\n- Use after free: accessing freed memory\n- Buffer overflow: writing past allocated size"},

    {"instruction": "Explain the x86-64 calling convention. How are function arguments passed?",
     "input": "", "output": "x86-64 System V AMD64 ABI (Linux/macOS):\n\nInteger/pointer arguments (first 6):\n  RDI, RSI, RDX, RCX, R8, R9\n\nFloating-point arguments (first 8):\n  XMM0 - XMM7\n\nReturn value:\n  Integer: RAX\n  Floating-point: XMM0\n\nStack-based arguments: 7th integer argument and beyond are pushed on the stack (right to left)\n\nExample:\nint foo(int a, int b, int c, int d, int e, int f, int g, int h)\n  a → RDI, b → RSI, c → RDX, d → RCX\n  e → R8,  f → R9,  g → [stack+0], h → [stack+8]\n\nCaller-saved (volatile) registers:\n  RAX, RCX, RDX, RSI, RDI, R8, R9, R10, R11\n  Function may modify these freely; caller must save if needed\n\nCallee-saved (non-volatile) registers:\n  RBX, RBP, R12, R13, R14, R15\n  Function must preserve these; restore before returning\n\nStack alignment:\n  The stack must be 16-byte aligned before CALL instruction\n  (RSP % 16 == 0 at the call site)\n\nThis differs from Windows x64 which uses: RCX, RDX, R8, R9 for first 4 args and shadow space."},

    {"instruction": "Explain how a linker works. What is the difference between static linking and dynamic linking?",
     "input": "", "output": "Linker combines object files (.o) into an executable or library.\n\nLinking process:\n1. Symbol Resolution: Match each symbol reference with its definition across all object files\n2. Relocation: Assign final memory addresses and patch all address references\n\nStatic Linking:\n- Copies all library code into the executable at link time\n- Result: Single self-contained executable\n- Pros: No dependencies, always works, faster startup\n- Cons: Larger binary, library updates require recompilation\n- Example: gcc -static hello.c -o hello\n\nDynamic Linking:\n- Stores references to shared libraries (.so / .dll)\n- Library code is loaded at runtime by the dynamic linker (ld.so)\n- Pros: Smaller binary, library updates without recompilation, shared memory\n- Cons: Dependency on .so files, slightly slower startup, version conflicts\n- Example: gcc hello.c -o hello (default)\n\nHow dynamic linking works at runtime:\n1. Kernel loads executable and maps it into memory\n2. Interpreter (ld-linux.so) is loaded\n3. ld-linux resolves shared library dependencies\n4. Libraries are mapped using mmap()\n5. GOT (Global Offset Table) and PLT (Procedure Linkage Table) enable lazy binding\n\nLazy binding: Function addresses are resolved on first call, not at startup.\nThis is why LD_BIND_NOW=1 disables lazy binding (for security/speed)."},

    {"instruction": "Explain the Linux boot process from power-on to user space.",
     "input": "", "output": "Linux Boot Process:\n\n1. BIOS/UEFI (Firmware)\n   - POST (Power-On Self-Test): check hardware\n   - Find boot device (disk, network, USB)\n   - Load first sector (MBR) or EFI partition\n\n2. Bootloader (GRUB2)\n   - Stage 1: MBR code (446 bytes), loads stage 2\n   - Stage 2: Reads /boot/grub/grub.cfg\n   - Loads vmlinuz (kernel) and initramfs into memory\n   - Passes command line parameters\n   - Transfers control to kernel\n\n3. Kernel Initialization\n   - Decompress vmlinuz (self-extracting)\n   - Setup: page tables, IDT, memory allocator\n   - Detect CPU features, enumerate PCI devices\n   - Load built-in drivers\n   - Mount initramfs as temporary root\n\n4. initramfs (Initial RAM Filesystem)\n   - Contains: udev, essential drivers, LVM/cryptsetup\n   - Loads modules needed to mount real root filesystem\n   - Mounts real root (/) via pivot_root()\n\n5. PID 1 (init/systemd)\n   - First userspace process\n   - systemd: reads unit files, starts services in parallel\n   - Mounts filesystems (/etc/fstab)\n   - Starts getty (login prompt) or display manager\n\n6. User Login\n   - getty prompts for username\n   - login verifies password (/etc/shadow)\n   - Starts shell (bash/zsh) with user's environment\n\nTotal time: ~2-10 seconds on modern hardware."},

    {"instruction": "Explain how TCP congestion control works. What is slow start, congestion avoidance, and fast recovery?",
     "input": "", "output": "TCP Congestion Control:\n\nGoal: Send data as fast as possible without overwhelming the network.\n\nKey variables:\n- cwnd (congestion window): how many bytes sender can have in-flight\n- ssthresh (slow start threshold): boundary between slow start and congestion avoidance\n- rtt (round-trip time): time for packet + ACK\n\nThree phases:\n\n1. Slow Start:\n   - Initial: cwnd = 1 MSS (maximum segment size, typically 1460 bytes)\n   - Each ACK: cwnd += 1 MSS (exponential growth)\n   - 1→2→4→8→16→32... doubles every RTT\n   - Continues until cwnd >= ssthresh or packet loss\n   - 'Slow' refers to starting from 1, but growth is actually exponential\n\n2. Congestion Avoidance:\n   - When cwnd >= ssthresh\n   - Each ACK: cwnd += MSS * (MSS/cwnd) (linear growth, +1 MSS per RTT)\n   - Much slower growth than slow start\n   - Continues until packet loss\n\n3. Fast Recovery (after 3 duplicate ACKs):\n   - ssthresh = cwnd / 2\n   - cwnd = ssthresh + 3*MSS\n   - Retransmit lost packet (fast retransmit)\n   - For each additional dup ACK: cwnd += MSS\n   - When new ACK arrives: cwnd = ssthresh, enter congestion avoidance\n\nTimeout (severe congestion):\n   - ssthresh = cwnd / 2\n   - cwnd = 1 MSS\n   - Go back to slow start\n\nThis is TCP Reno. TCP CUBIC (default in Linux) uses a cubic function instead of linear growth in congestion avoidance."},

    {"instruction": "Explain how a compiler works. What are the main phases of compilation?",
     "input": "", "output": "Compiler Phases:\n\n1. Lexical Analysis (Scanner/Tokenizer)\n   - Input: source code (character stream)\n   - Output: token stream\n   - Removes whitespace and comments\n   - Example: 'int x = 42;' → [INT, ID('x'), ASSIGN, NUM(42), SEMI]\n   - Tool: flex/lex (regex-based)\n\n2. Syntax Analysis (Parser)\n   - Input: token stream\n   - Output: Abstract Syntax Tree (AST)\n   - Checks grammatical structure using context-free grammar\n   - Example: AST node: Assignment(var='x', value=IntLiteral(42))\n   - Tool: bison/yacc (LALR parser), or hand-written recursive descent\n\n3. Semantic Analysis\n   - Type checking: int x = 'hello' → ERROR\n   - Symbol table: variable declarations, scope resolution\n   - Implicit conversions: int x = 3.14 → warning or conversion\n   - Output: decorated AST with type information\n\n4. Intermediate Code Generation\n   - Convert AST to intermediate representation (IR)\n   - LLVM IR, Three-address code, SSA form\n   - Example: x = 42 → store i32 42, i32* %x\n\n5. Optimization\n   - Constant folding: x = 2+3 → x = 5\n   - Dead code elimination: remove unused variables\n   - Loop optimization: unrolling, vectorization\n   - Inlining: replace function calls with body\n   - Register allocation: map temporaries to CPU registers\n\n6. Code Generation\n   - Convert optimized IR to target machine code\n   - Instruction selection, scheduling\n   - Output: assembly or object file (.o)\n\n7. Linking (separate program)\n   - Combine object files + libraries → executable\n\nModern compilers (LLVM, GCC) have many more optimization passes and support multiple frontends (C, C++, Rust, Swift) sharing the same backend."},

    {"instruction": "Explain what a system call is. How does the transition from user mode to kernel mode work?",
     "input": "", "output": "System Call:\nA system call is the interface between user programs and the kernel. When a program needs privileged operations (I/O, memory, processes), it must ask the kernel via a syscall.\n\nCommon syscalls:\n- read/write: file I/O\n- open/close: file management\n- fork/exec: process creation\n- mmap: memory mapping\n- socket/connect: networking\n- ioctl: device control\n\nUser → Kernel transition:\n\n1. User program calls libc wrapper (e.g., write())\n2. Wrapper puts syscall number in RAX, args in RDI/RSI/RDX\n3. Wrapper executes SYSCALL instruction (x86-64)\n4. CPU switches to kernel mode (ring 0)\n5. CPU jumps to syscall entry point (MSR_LSTAR)\n6. Kernel saves user registers on kernel stack\n7. Kernel looks up syscall number in sys_call_table[]\n8. Kernel executes the syscall handler\n9. Kernel restores user registers, puts return value in RAX\n10. Executes SYSRET instruction\n11. CPU returns to user mode (ring 3)\n12. User program continues\n\nCost of syscall:\n- ~200-1000 nanoseconds (vs ~1ns for function call)\n- Must flush TLB entries, switch stacks\n- This is why buffered I/O (libc) is faster than raw syscalls\n\n/proc/sys/kernel/syscall: list of available syscalls\nstrace: tool to trace syscalls made by a program"},

    {"instruction": "Explain the concept of virtualization. How do hypervisors work?",
     "input": "", "output": "Virtualization allows multiple operating systems to run simultaneously on one physical machine.\n\nType 1 Hypervisor (Bare Metal):\n- Runs directly on hardware\n- Examples: VMware ESXi, Xen, Hyper-V, KVM\n- Better performance, used in data centers\n\nType 2 Hypervisor (Hosted):\n- Runs on top of a host OS\n- Examples: VirtualBox, VMware Workstation, QEMU\n- Easier to use, slower performance\n\nHow it works:\n\n1. CPU Virtualization:\n   - Trap-and-emulate: guest executes privileged instructions → trap to hypervisor\n   - Hardware-assisted: Intel VT-x / AMD-V provide VMX root/non-root modes\n   - VMCS (Virtual Machine Control Structure) stores guest state\n\n2. Memory Virtualization:\n   - Extended Page Tables (EPT): hardware walks guest→host page tables\n   - Shadow page tables: hypervisor maintains combined mappings\n   - Each guest sees contiguous physical memory (actually scattered in host)\n\n3. I/O Virtualization:\n   - Emulation: hypervisor emulates devices (slow but compatible)\n   - Paravirtualization: guest uses special drivers (virtio) for better performance\n   - Passthrough: direct device access (SR-IOV, VFIO) for maximum performance\n\nKVM (Linux):\n- Turns Linux kernel into a Type 1 hypervisor\n- Each VM is a regular Linux process\n- Uses QEMU for device emulation\n- virtio drivers for paravirtualized I/O\n- This is what cloud providers (AWS, GCP) use"},

    {"instruction": "Explain the CAP theorem. What are the trade-offs in distributed systems?",
     "input": "", "output": "CAP Theorem:\nIn a distributed system, you can only guarantee TWO of the following THREE:\n\nC - Consistency: All nodes see the same data at the same time\nA - Availability: Every request receives a response (not an error)\nP - Partition tolerance: System continues despite network failures\n\nSince network partitions (P) are inevitable in distributed systems, the real choice is:\n\nCP (Consistency + Partition tolerance):\n- When partition occurs, refuse some requests to maintain consistency\n- Examples: ZooKeeper, etcd, HBase, MongoDB (default)\n- Use case: banking, inventory management\n- Trade-off: may be unavailable during partitions\n\nAP (Availability + Partition tolerance):\n- When partition occurs, keep serving requests, accept inconsistency\n- Examples: Cassandra, DynamoDB, CouchDB, DNS\n- Use case: social media, shopping carts, caching\n- Trade-off: reads may return stale data (eventual consistency)\n\nImportant nuance:\n- CAP only applies during network partitions\n- When network is healthy, you can have both C and A\n- Modern systems often provide tunable consistency (e.g., Cassandra's consistency level)\n\nPACELC theorem (extension of CAP):\nIf Partition: choose Availability or Consistency\nElse: choose Latency or Consistency\n\nThis better reflects real-world trade-offs: even without partitions, there's a latency-consistency trade-off."},

    {"instruction": "Explain how a hash table works. What are collisions and how are they resolved?",
     "input": "", "output": "Hash Table:\nA data structure that maps keys to values using a hash function for O(1) average lookup.\n\nHow it works:\n1. Hash function h(key) maps key to an integer index\n2. Index = h(key) % table_size\n3. Store key-value pair at that index in an array (called buckets)\n\nGood hash function properties:\n- Deterministic: same key always same hash\n- Uniform distribution: spread keys evenly\n- Fast to compute\n- Examples: murmurhash, cityhash, FNV\n\nCollisions:\nWhen two different keys hash to the same index.\n\nResolution strategies:\n\n1. Chaining (Open Hashing):\n   - Each bucket contains a linked list\n   - Collision: append to the list\n   - Lookup: hash → traverse list → find key\n   - Pros: simple, handles any load factor\n   - Cons: pointer chasing, cache-unfriendly\n\n2. Open Addressing (Closed Hashing):\n   - All entries in the array itself\n   - Collision: probe for next empty slot\n   - Linear probing: try index+1, index+2, ...\n   - Quadratic probing: try index+1², index+2², ...\n   - Double hashing: try index + h2(key), index + 2*h2(key)\n   - Pros: cache-friendly, no pointers\n   - Cons: clustering, sensitive to load factor\n\nLoad factor = n/m (entries/buckets)\n- Chaining: OK up to ~0.75\n- Open addressing: resize at ~0.5-0.7\n- Python dict: resize at 2/3 full\n- Java HashMap: resize at 0.75 load factor\n\nTime complexity:\n- Average: O(1) for insert/lookup/delete\n- Worst: O(n) when all keys collide"},

    {"instruction": "Explain the Raft consensus algorithm. How does it ensure consistency in distributed systems?",
     "input": "", "output": "Raft is a consensus algorithm for managing a replicated log across multiple servers. It's designed to be understandable (unlike Paxos).\n\nKey Concepts:\n\n1. Leader Election:\n   - One server is the leader, others are followers\n   - Leader sends heartbeats to maintain authority\n   - If follower doesn't hear from leader (election timeout), it becomes candidate\n   - Candidate requests votes from other servers\n   - Server with majority votes becomes new leader\n   - Term number increases with each election\n\n2. Log Replication:\n   - Client sends command to leader\n   - Leader appends to its log, sends AppendEntries to followers\n   - Once majority replicate → entry is committed\n   - Leader notifies followers of committed entries\n   - Guarantees: if two logs have same index and term, all preceding entries are identical\n\n3. Safety:\n   - Leader completeness: any committed entry is present in all future leaders' logs\n   - A server won't vote for candidate whose log is less up-to-date\n   - Commit only when current-term entry is replicated on majority\n\nRaft vs Paxos:\n- Raft: leader-based, easier to understand and implement\n- Paxos: leaderless, more complex but more flexible\n\nUsed by: etcd, Consul, CockroachDB, TiKV\n\nTypical cluster: 3 or 5 nodes (tolerates 1 or 2 failures)"},

    {"instruction": "Explain how CUDA programming works. What is the relationship between grids, blocks, and threads?",
     "input": "", "output": "CUDA (Compute Unified Device Architecture):\nNVIDIA's platform for general-purpose GPU computing.\n\nExecution Hierarchy:\n1. Grid: A kernel launch creates one grid\n2. Block (Thread Block): Grid is divided into blocks (max 1024 threads/block)\n3. Thread: Each block contains multiple threads\n\nExample: Processing 1M elements\n- Grid: 1D grid of 1000 blocks\n- Block: 1D block of 1024 threads\n- Total: 1,024,000 threads (more than needed, some idle)\n\nMemory Hierarchy:\n1. Global Memory: all threads can access, high latency (~400 cycles)\n2. Shared Memory: per-block, low latency (~20 cycles), 48KB-96KB\n3. Registers: per-thread, fastest, limited (~255 per thread)\n4. Constant Memory: read-only, cached\n5. Texture Memory: read-only, 2D spatial locality\n\nSimple CUDA kernel:\n__global__ void vectorAdd(float *a, float *b, float *c, int n) {\n    int i = blockIdx.x * blockDim.x + threadIdx.x;\n    if (i < n) c[i] = a[i] + b[i];\n}\n\nLaunch: vectorAdd<<<numBlocks, blockSize>>>(d_a, d_b, d_c, n);\n\nKey optimization techniques:\n- Coalesced memory access: consecutive threads access consecutive addresses\n- Shared memory tiling: load tile into shared memory, compute, write back\n- Warp-level primitives: __shfl_sync() for fast inter-thread communication\n- Stream overlap: overlap kernel execution with memory transfers\n\nA warp is 32 threads that execute together in lockstep (SIMD). Divergent branches within a warp cause serialization."},

    {"instruction": "Explain the concept of a B-tree. Why are B-trees used in databases instead of binary search trees?",
     "input": "", "output": "B-tree:\nA self-balancing tree where each node can have multiple children (not just 2). Commonly used in databases and file systems.\n\nProperties of B-tree of order m:\n- Every node has at most m children\n- Every non-leaf node (except root) has at least ⌈m/2⌉ children\n- Root has at least 2 children (if not leaf)\n- All leaves appear at the same level\n- A non-leaf node with k children has k-1 keys\n\nWhy B-trees over BSTs in databases:\n\n1. Disk I/O optimization:\n   - BST: O(log n) height, but each node is 1 disk read\n   - B-tree: O(log_m(n)) height, but each node is 1 disk read\n   - With m=100: B-tree is ~7x shallower than BST for 1M keys\n   - Each B-tree node fits in one disk page (4-8KB)\n\n2. Cache-friendly:\n   - B-tree nodes contain many keys → one disk read gets many comparisons\n   - Binary tree: one key per node → one disk read per comparison\n\n3. Fewer rebalancing operations:\n   - B-tree splits/merges are less frequent\n   - Better write performance for databases\n\nB+ tree (variant used in most databases):\n- All data in leaf nodes\n- Internal nodes only store keys for routing\n- Leaf nodes linked together (sequential access)\n- Used by: MySQL InnoDB, PostgreSQL, SQLite, NTFS, ext4\n\nFanout example:\n- 4KB page, 8-byte key + 8-byte pointer = 16 bytes per entry\n- Fanout = 4096/16 = 256 children per node\n- 3-level B+ tree holds: 256³ = 16.7 million keys"},

    {"instruction": "Explain the difference between concurrency and parallelism. What are common concurrency bugs?",
     "input": "", "output": "Concurrency vs Parallelism:\n\nConcurrency: Dealing with multiple things at once (structure)\n- Multiple tasks make progress on 1 core (time-slicing)\n- About design: how to structure a program with multiple logical tasks\n- Example: web server handling 1000 connections on 1 CPU\n\nParallelism: Doing multiple things at once (execution)\n- Multiple tasks execute simultaneously on multiple cores\n- About performance: how to use hardware efficiently\n- Example: matrix multiplication on 8 CPU cores\n\nConcurrency ≠ Parallelism:\n- Concurrency without parallelism: single-core multitasking\n- Parallelism without concurrency: SIMD instructions on one data stream\n- Best: concurrent design + parallel execution\n\nCommon Concurrency Bugs:\n\n1. Race Condition:\n   Two threads access shared data, outcome depends on timing\n   x = 0; Thread1: x++; Thread2: x++; // x might be 1 or 2\n   Fix: mutex lock, atomic operations\n\n2. Data Race (special case of race condition):\n   At least one access is a write, no synchronization\n   Fix: std::atomic, memory barriers\n\n3. Deadlock:\n   Circular wait for locks\n   Fix: lock ordering, trylock with timeout\n\n4. Livelock:\n   Threads keep responding to each other but make no progress\n   Fix: random backoff\n\n5. Priority Inversion:\n   Low-priority thread holds lock needed by high-priority thread\n   Fix: priority inheritance protocol\n\n6. ABA Problem:\n   Value changes A→B→A, appears unchanged\n   Fix: version counters, hazard pointers"},

    {"instruction": "Explain how garbage collection works. Compare mark-and-sweep, copying, and generational GC.",
     "input": "", "output": "Garbage Collection (GC) automatically reclaims memory that's no longer reachable.\n\n1. Mark-and-Sweep:\n   Phase 1 (Mark): Start from roots (stack, globals), traverse all reachable objects, mark them\n   Phase 2 (Sweep): Scan all memory, free unmarked objects\n   Pros: Simple, handles cycles\n   Cons: Fragmentation, pause time proportional to heap size, cache-unfriendly\n   Used by: Go (old), Ruby, early Java\n\n2. Copying (Cheney's algorithm):\n   Divide heap into two semi-spaces (from-space, to-space)\n   Allocate in from-space\n   When full: copy reachable objects to to-space (compacts), swap spaces\n   Pros: No fragmentation, fast allocation (bump pointer)\n   Cons: Uses 2x memory, copying cost proportional to live data\n   Used by: OCaml, Erlang, young generation in most GCs\n\n3. Generational GC:\n   Observation: most objects die young (>90%)\n   Divide heap into generations:\n   - Young generation (nursery): new objects, frequent collection\n   - Old generation: survived objects, rare collection\n   Minor GC: collect only young gen (fast, most garbage here)\n   Major GC: collect all generations (slow, rare)\n   Write barrier: track old→young references for minor GC\n   Pros: Very efficient for typical workloads\n   Cons: Write barrier overhead, more complex\n   Used by: Java (G1/ZGC), Python, .NET, V8 (JavaScript)\n\nPython's GC: Reference counting + generational backup for cycles\nGo's GC: Concurrent tri-color mark-and-sweep (low latency)\nJava's GC: G1 (default), ZGC (sub-millisecond pauses), Shenandoah"},
]

path = os.path.join(OUT, "cezanne_stage3_cs_v1.json")
with open(path, "w", encoding="utf-8") as f:
    json.dump(CS_DATA, f, ensure_ascii=False, indent=2)
print(f"  CS S3 data: {len(CS_DATA)}条 → {path}")
print(f"  Coverage: OS/内存/并发/编译/网络/分布式/CUDA/数据结构/GC/虚拟化")
