#!/usr/bin/env python3
"""Generate rescue data for 7B Cezanne: debug + logic2 + graph preservation"""
import json, os, sys
sys.stdout.reconfigure(encoding='utf-8', errors='replace')

OUT = r"D:\VORTEX_FLAME\soul_training_data\cezanne"

DEBUG_DATA = [
    {"instruction": "Find the bug in this binary search. Explain what's wrong and fix it:\ndef binary_search(arr, target):\n    left, right = 0, len(arr)\n    while left < right:\n        mid = (left + right) // 2\n        if arr[mid] == target:\n            return mid\n        elif arr[mid] < target:\n            left = mid\n        else:\n            right = mid\n    return -1",
     "input": "", "output": "Bug: When arr[mid] < target, we set left = mid instead of left = mid + 1. This causes an infinite loop when left = mid and the search space doesn't shrink.\n\nSimilarly, when arr[mid] > target, we set right = mid instead of right = mid - 1 (or keep right = mid if using half-open interval).\n\nThe issue is off-by-one: the search interval doesn't shrink on one side.\n\nFix:\ndef binary_search(arr, target):\n    left, right = 0, len(arr) - 1\n    while left <= right:\n        mid = (left + right) // 2\n        if arr[mid] == target:\n            return mid\n        elif arr[mid] < target:\n            left = mid + 1\n        else:\n            right = mid - 1\n    return -1\n\nKey changes:\n1. right = len(arr) - 1 (closed interval)\n2. while left <= right (not <)\n3. left = mid + 1 (skip mid, already checked)\n4. right = mid - 1 (skip mid, already checked)\n\nThis ensures the boundary always shrinks, preventing infinite loops."},

    {"instruction": "Find the bug in this code that should print numbers 1 to 10:\nfor i in range(10):\n    print(i)",
     "input": "", "output": "Bug: range(10) produces 0 to 9, not 1 to 10.\n\nFix: Use range(1, 11) instead.\n\nfor i in range(1, 11):\n    print(i)\n\nThis is an off-by-one error, one of the most common bugs in programming. Always check whether your range boundaries are inclusive or exclusive."},

    {"instruction": "Find the bug in this factorial function:\ndef factorial(n):\n    if n == 0:\n        return 0\n    return n * factorial(n - 1)",
     "input": "", "output": "Bug: factorial(0) should return 1, not 0. The base case is wrong.\n\n0! = 1 by definition. Returning 0 makes every factorial result 0 because anything multiplied by 0 is 0.\n\nFix:\ndef factorial(n):\n    if n == 0:\n        return 1\n    return n * factorial(n - 1)\n\nNow factorial(5) = 5 * 4 * 3 * 2 * 1 * 1 = 120, which is correct."},

    {"instruction": "Find the bug in this code that reverses a list:\ndef reverse_list(lst):\n    result = []\n    for i in range(len(lst)):\n        result.append(lst[i])\n    return result",
     "input": "", "output": "Bug: The code just copies the list in the same order. It iterates from index 0 to len-1, appending each element. This produces an identical copy, not a reversal.\n\nFix: Iterate from the end:\ndef reverse_list(lst):\n    result = []\n    for i in range(len(lst) - 1, -1, -1):\n        result.append(lst[i])\n    return result\n\nOr simply: return lst[::-1]\n\nThe bug was a logic error — the iteration direction was wrong."},

    {"instruction": "Find the bug in this code to check if a string is a palindrome:\ndef is_palindrome(s):\n    return s == s[::-1] and len(s) > 0",
     "input": "", "output": "Potential issue: This doesn't handle case sensitivity or spaces. 'Race car' would return False but should be True.\n\nImproved version:\ndef is_palindrome(s):\n    cleaned = ''.join(c.lower() for c in s if c.isalnum())\n    return cleaned == cleaned[::-1] and len(cleaned) > 0\n\nThis removes spaces and punctuation, and converts to lowercase before comparing."},

    {"instruction": "Find the bug in this merge sort:\ndef merge_sort(arr):\n    if len(arr) <= 1:\n        return arr\n    mid = len(arr) // 2\n    left = merge_sort(arr[:mid])\n    right = merge_sort(arr[mid:])\n    return merge(left, right)\n\ndef merge(left, right):\n    result = []\n    i = j = 0\n    while i < len(left) and j < len(right):\n        if left[i] <= right[j]:\n            result.append(left[i])\n            i += 1\n        else:\n            result.append(right[j])\n            j += 1\n    return result",
     "input": "", "output": "Bug: The merge function doesn't append the remaining elements after the while loop. When one list is exhausted, the remaining elements of the other list are lost.\n\nFix:\ndef merge(left, right):\n    result = []\n    i = j = 0\n    while i < len(left) and j < len(right):\n        if left[i] <= right[j]:\n            result.append(left[i])\n            i += 1\n        else:\n            result.append(right[j])\n            j += 1\n    result.extend(left[i:])\n    result.extend(right[j:])\n    return result\n\nThe two extend() calls at the end handle the remaining elements. This is a classic boundary condition bug."},

    {"instruction": "Find the bug in this code to remove duplicates from a sorted list:\ndef remove_duplicates(lst):\n    i = 0\n    while i < len(lst) - 1:\n        if lst[i] == lst[i + 1]:\n            lst.pop(i)\n        i += 1\n    return lst",
     "input": "", "output": "Bug: After popping an element at index i, the next element shifts to index i. But the code increments i anyway, skipping the element that just moved to position i.\n\nExample: [1,1,2,2] → pop index 0 → [1,2,2] → i becomes 1 → we skip checking index 1 against index 2.\n\nFix: Only increment i when no pop occurs:\ndef remove_duplicates(lst):\n    i = 0\n    while i < len(lst) - 1:\n        if lst[i] == lst[i + 1]:\n            lst.pop(i)\n        else:\n            i += 1\n    return lst\n\nThis is a mutation-during-iteration bug — when you remove an element, the indices shift."},

    {"instruction": "Debug this Python code that should find the second largest number:\ndef second_largest(numbers):\n    largest = second = float('-inf')\n    for n in numbers:\n        if n > largest:\n            second = largest\n            largest = n\n    return second",
     "input": "", "output": "Bug: When n is not larger than largest but is larger than second, we don't update second. For example, [5, 3, 5] would return -inf instead of 5.\n\nFix:\ndef second_largest(numbers):\n    largest = second = float('-inf')\n    for n in numbers:\n        if n > largest:\n            second = largest\n            largest = n\n        elif n > second and n != largest:\n            second = n\n    return second\n\nThe elif clause handles the case where n is between second and largest. The n != largest check prevents counting duplicates of the largest as the second largest."},

    {"instruction": "Debug this linked list cycle detection:\ndef has_cycle(head):\n    slow = fast = head\n    while fast and fast.next:\n        slow = slow.next\n        fast = fast.next.next\n        if slow == fast:\n            return True\n    return False\n\nWhat happens if head is None?",
     "input": "", "output": "The code is actually correct! When head is None:\n- slow = fast = None\n- The while condition 'fast and fast.next' evaluates to False immediately\n- Returns False, which is correct (empty list has no cycle)\n\nThis is Floyd's cycle detection algorithm (tortoise and hare). The code handles all edge cases:\n- None head → False ✓\n- Single node, no cycle → False ✓\n- Single node with self-loop → True ✓\n- Long list with cycle → True ✓\n\nNo bug here. This is a well-implemented algorithm."},

    {"instruction": "Debug this SQL query that should find users who made more than 5 orders:\nSELECT user_id FROM orders WHERE COUNT(*) > 5;",
     "input": "", "output": "Bug: You cannot use aggregate functions like COUNT(*) in a WHERE clause. WHERE filters rows before grouping.\n\nFix: Use HAVING clause after GROUP BY:\nSELECT user_id FROM orders GROUP BY user_id HAVING COUNT(*) > 5;\n\nExplanation:\n- WHERE filters individual rows before aggregation\n- GROUP BY groups rows by user_id\n- HAVING filters groups after aggregation\n\nThis is one of the most common SQL mistakes — confusing WHERE and HAVING."},

    {"instruction": "Debug this recursive Fibonacci that's extremely slow:\ndef fib(n):\n    if n <= 1:\n        return n\n    return fib(n-1) + fib(n-2)\n\nHow to fix the performance?",
     "input": "", "output": "Bug: Exponential time complexity O(2^n) due to redundant calculations. fib(5) calls fib(4) and fib(3), but fib(4) also calls fib(3) again.\n\nFix 1 — Memoization:\nfrom functools import lru_cache\n@lru_cache(maxsize=None)\ndef fib(n):\n    if n <= 1:\n        return n\n    return fib(n-1) + fib(n-2)\n\nFix 2 — Iterative (O(n) time, O(1) space):\ndef fib(n):\n    if n <= 1:\n        return n\n    a, b = 0, 1\n    for _ in range(2, n + 1):\n        a, b = b, a + b\n    return b\n\nThe iterative version is best: no recursion depth limit, O(n) time, O(1) space."},

    {"instruction": "Debug this code that should find all pairs summing to target:\ndef find_pairs(arr, target):\n    pairs = []\n    for i in range(len(arr)):\n        for j in range(len(arr)):\n            if arr[i] + arr[j] == target:\n                pairs.append((arr[i], arr[j]))\n    return pairs",
     "input": "", "output": "Bugs:\n1. j starts from 0, so it pairs each element with itself (arr[i] + arr[i] == target is checked)\n2. Duplicate pairs: (3,5) and (5,3) are both included\n\nFix:\ndef find_pairs(arr, target):\n    pairs = []\n    seen = set()\n    for num in arr:\n        complement = target - num\n        if complement in seen:\n            pairs.append((min(num, complement), max(num, complement)))\n        seen.add(num)\n    return list(set(pairs))\n\nThis uses a hash set for O(n) time, avoids self-pairing, and removes duplicates."},

    {"instruction": "Debug this code that should shuffle a list randomly:\nimport random\ndef shuffle(lst):\n    for i in range(len(lst)):\n        j = random.randint(0, len(lst) - 1)\n        lst[i], lst[j] = lst[j], lst[i]\n    return lst",
     "input": "", "output": "Bug: This shuffle is NOT uniformly random. random.randint(0, len-1) picks from ALL indices, not just from i onward. This creates a biased distribution.\n\nFix — Fisher-Yates shuffle:\nimport random\ndef shuffle(lst):\n    for i in range(len(lst) - 1, 0, -1):\n        j = random.randint(0, i)\n        lst[i], lst[j] = lst[j], lst[i]\n    return lst\n\nKey difference: j is chosen from [0, i], not [0, len-1]. Each element has exactly 1/n probability of ending up in any position. The original code has n^n possible outcomes, which cannot be evenly distributed among n! permutations."},

    {"instruction": "Debug this BFS implementation:\nfrom collections import deque\ndef bfs(graph, start):\n    visited = set()\n    queue = deque([start])\n    while queue:\n        node = queue.popleft()\n        visited.add(node)\n        for neighbor in graph[node]:\n            if neighbor not in visited:\n                queue.append(neighbor)\n    return visited",
     "input": "", "output": "Bug: A node can be added to the queue multiple times before it's visited. When we check 'if neighbor not in visited', the neighbor might already be in the queue but not yet visited.\n\nFor example, if node A and B both connect to C, C gets added twice.\n\nFix — check when adding to queue, not when visiting:\nfrom collections import deque\ndef bfs(graph, start):\n    visited = set([start])\n    queue = deque([start])\n    while queue:\n        node = queue.popleft()\n        for neighbor in graph[node]:\n            if neighbor not in visited:\n                visited.add(neighbor)\n                queue.append(neighbor)\n    return visited\n\nKey change: mark as visited when ENQUEUING, not when DEQUEUING. This prevents duplicate entries."},

    {"instruction": "Debug this code that should count words in a string:\ndef count_words(text):\n    return len(text.split())",
     "input": "", "output": "This works for simple cases but has edge cases:\n1. Multiple spaces: 'hello  world' → split() handles this ✓\n2. Leading/trailing spaces: '  hello  ' → split() handles this ✓\n3. Empty string: '' → split() returns [] → len = 0 ✓\n4. But: it counts punctuation-attached words as different: 'hello.' vs 'hello'\n5. It doesn't handle hyphens: 'well-known' counts as one word\n\nFor most use cases, this is fine. For more precise counting:\nimport re\ndef count_words(text):\n    words = re.findall(r\"\\b[a-zA-Z'-]+\\b\", text)\n    return len(words)\n\nBut the original code is not buggy — it's just simple. The 'bug' is in requirements ambiguity."},

    {"instruction": "Debug this thread-unsafe counter:\nclass Counter:\n    def __init__(self):\n        self.count = 0\n    def increment(self):\n        self.count += 1",
     "input": "", "output": "Bug: self.count += 1 is NOT atomic. It's actually: read → add 1 → write. Two threads can read the same value, both add 1, and write the same result, losing one increment.\n\nFix with threading.Lock:\nimport threading\nclass Counter:\n    def __init__(self):\n        self.count = 0\n        self.lock = threading.Lock()\n    def increment(self):\n        with self.lock:\n            self.count += 1\n\nThe lock ensures only one thread can increment at a time. This is a classic race condition bug — the most common concurrency error."},

    {"instruction": "Debug this code that should read a file safely:\ndef read_file(path):\n    f = open(path, 'r')\n    data = f.read()\n    f.close()\n    return data",
     "input": "", "output": "Bug: If an exception occurs between open() and close(), the file handle leaks. The file stays open until garbage collection.\n\nFix — use context manager:\ndef read_file(path):\n    with open(path, 'r') as f:\n        data = f.read()\n    return data\n\nThe 'with' statement guarantees close() is called even if an exception occurs. This is Python best practice for resource management."},

    {"instruction": "Debug this code that should check if a number is prime:\ndef is_prime(n):\n    if n < 2:\n        return False\n    for i in range(2, n):\n        if n % i == 0:\n            return False\n    return True\n\nHow to optimize?",
     "input": "", "output": "The code is correct but inefficient. It checks all numbers from 2 to n-1, giving O(n) time.\n\nOptimizations:\n1. Only check up to sqrt(n): if n has a factor > sqrt(n), it must have a corresponding factor < sqrt(n)\n2. Skip even numbers after checking 2\n\ndef is_prime(n):\n    if n < 2:\n        return False\n    if n == 2:\n        return True\n    if n % 2 == 0:\n        return False\n    for i in range(3, int(n**0.5) + 1, 2):\n        if n % i == 0:\n            return False\n    return True\n\nThis reduces time from O(n) to O(sqrt(n)/2), a massive speedup for large n."},

    {"instruction": "Debug this regex that should match email addresses:\nimport re\npattern = r'^[a-zA-Z0-9]+@[a-zA-Z0-9]+\\.[a-zA-Z]{2,}$'\nprint(re.match(pattern, 'user.name+tag@example.co.uk'))",
     "input": "", "output": "Bug: The regex is too restrictive. It doesn't allow:\n1. Dots in the local part: user.name\n2. Plus signs: user+tag\n3. Multiple dots in domain: example.co.uk\n4. Hyphens in domain: my-domain.com\n\nBetter regex:\nimport re\npattern = r'^[a-zA-Z0-9._%+-]+@[a-zA-Z0-9.-]+\\.[a-zA-Z]{2,}$'\n\nThis allows common email formats. However, the full RFC 5322 email spec is extremely complex. For production, use a library like email-validator instead of regex."},

    {"instruction": "Debug this code that should flatten a nested list:\ndef flatten(lst):\n    result = []\n    for item in lst:\n        if isinstance(item, list):\n            result.extend(flatten(item))\n        else:\n            result.append(item)\n    return result\n\nWhat's the potential issue?",
     "input": "", "output": "The code works correctly but has two potential issues:\n\n1. Recursion depth: Very deeply nested lists will hit Python's recursion limit (default 1000). Fix: increase limit or use iterative approach.\n\n2. Type checking: isinstance(item, list) won't catch tuples or other iterables. Fix:\ndef flatten(lst):\n    result = []\n    for item in lst:\n        if isinstance(item, (list, tuple)):\n            result.extend(flatten(item))\n        else:\n            result.append(item)\n    return result\n\nFor production, consider a generator approach for memory efficiency:\ndef flatten(lst):\n    for item in lst:\n        if isinstance(item, (list, tuple)):\n            yield from flatten(item)\n        else:\n            yield item"},
]

LOGIC2_DATA = [
    {"instruction": "Prove using formal logic: if P implies Q and Q implies R, then P implies R. This is called hypothetical syllogism.",
     "input": "", "output": "Hypothetical Syllogism Proof:\n\nGiven:\n1. P → Q (Premise 1)\n2. Q → R (Premise 2)\n\nTo prove: P → R\n\nProof:\nAssume P is true (for conditional proof).\nFrom premise 1 (P → Q) and our assumption P, by Modus Ponens we derive Q.\nFrom premise 2 (Q → R) and Q, by Modus Ponens we derive R.\nTherefore, from assumption P we have derived R.\nBy conditional proof, P → R. QED.\n\nThis is the transitivity of implication, also known as hypothetical syllogism or chain reasoning.\nFormal notation: (P → Q) ∧ (Q → R) ⊢ (P → R)"},

    {"instruction": "Prove using formal logic: if P or Q, and not P, then Q. This is called disjunctive syllogism.",
     "input": "", "output": "Disjunctive Syllogism Proof:\n\nGiven:\n1. P ∨ Q (Premise 1: P or Q)\n2. ¬P (Premise 2: not P)\n\nTo prove: Q\n\nProof:\nFrom premise 1, we know at least one of P or Q is true.\nFrom premise 2, we know P is false.\nSince P ∨ Q is true and P is false, Q must be true.\nTherefore, Q. QED.\n\nFormal notation: (P ∨ Q) ∧ ¬P ⊢ Q\n\nThis is one of the most fundamental rules of inference in propositional logic."},

    {"instruction": "Prove using Modus Ponens: If it rains, the ground is wet. It is raining. What can we conclude?",
     "input": "", "output": "Modus Ponens Application:\n\nGiven:\n1. R → W (If it rains, the ground is wet)\n2. R (It is raining)\n\nConclusion: W (The ground is wet)\n\nProof:\nModus Ponens states: If P → Q and P, then Q.\nHere P = R (raining), Q = W (wet ground).\nWe have both premises, so by Modus Ponens, W follows.\n\nFormal notation: (P → Q) ∧ P ⊢ Q\n\nNote: This does NOT mean 'if the ground is wet, it rained.' That would be the converse fallacy (affirming the consequent). The ground could be wet for other reasons."},

    {"instruction": "Prove using Modus Tollens: If the machine is working, the light is on. The light is not on. What can we conclude?",
     "input": "", "output": "Modus Tollens Application:\n\nGiven:\n1. W → L (If the machine is working, the light is on)\n2. ¬L (The light is not on)\n\nConclusion: ¬W (The machine is not working)\n\nProof:\nModus Tollens states: If P → Q and ¬Q, then ¬P.\nHere P = W (working), Q = L (light on).\nIf the machine were working, the light would be on (premise 1).\nBut the light is not on (premise 2).\nThis contradicts what would happen if the machine were working.\nTherefore, the machine is not working. QED.\n\nFormal notation: (P → Q) ∧ ¬Q ⊢ ¬P\n\nThis is the logical basis of proof by contrapositive."},

    {"instruction": "What is the difference between Modus Ponens and Modus Tollens? Give an example of each.",
     "input": "", "output": "Modus Ponens vs Modus Tollens:\n\nModus Ponens (affirming the antecedent):\n  If P → Q, and P is true, then Q is true.\n  Example: If it's a dog, it's a mammal. It's a dog. → It's a mammal.\n  Pattern: (P → Q) ∧ P ⊢ Q\n\nModus Tollens (denying the consequent):\n  If P → Q, and Q is false, then P is false.\n  Example: If it's a dog, it's a mammal. It's not a mammal. → It's not a dog.\n  Pattern: (P → Q) ∧ ¬Q ⊢ ¬P\n\nBoth are VALID forms of reasoning.\n\nCommon FALLACIES to avoid:\n- Affirming the consequent: P → Q, Q, therefore P (INVALID)\n  Example: If it's a dog, it's a mammal. It's a mammal. → It's a dog? NO, could be a cat.\n- Denying the antecedent: P → Q, ¬P, therefore ¬Q (INVALID)\n  Example: If it's a dog, it's a mammal. It's not a dog. → It's not a mammal? NO, could be a cat."},

    {"instruction": "Prove by contradiction: If P implies Q, and not Q, then not P.",
     "input": "", "output": "Proof by Contradiction (Modus Tollens variant):\n\nGiven:\n1. P → Q\n2. ¬Q\n\nTo prove: ¬P\n\nProof:\nAssume, for contradiction, that P is true.\nFrom premise 1 (P → Q) and our assumption P, by Modus Ponens, Q must be true.\nBut premise 2 states ¬Q (Q is false).\nThis is a contradiction: Q and ¬Q cannot both be true.\nTherefore, our assumption that P is true must be false.\nHence, ¬P. QED.\n\nThis is essentially Modus Tollens proven via contradiction.\nFormal notation: (P → Q) ∧ ¬Q ⊢ ¬P"},

    {"instruction": "What is a logical fallacy? Explain 'affirming the consequent' with an example.",
     "input": "", "output": "A logical fallacy is an invalid argument that appears logical but has a flaw in reasoning.\n\nAffirming the Consequent (INVALID):\nPattern: If P then Q. Q is true. Therefore P is true.\n\nExample:\nIf it's raining, the ground is wet. (P → Q)\nThe ground is wet. (Q)\nTherefore, it's raining. (P?) ← INVALID!\n\nWhy it's wrong: The ground could be wet for other reasons (sprinkler, spilled water, etc.). Q being true doesn't necessarily mean P caused it.\n\nThe VALID form is Modus Ponens:\nIf P then Q. P is true. Therefore Q is true.\n\nKey insight: P → Q means 'whenever P, then Q.' It does NOT mean 'whenever Q, then P.' That would be Q → P (the converse), which is a different statement entirely."},

    {"instruction": "Prove the contrapositive: If P implies Q, then not-Q implies not-P.",
     "input": "", "output": "Contrapositive Proof:\n\nGiven: P → Q\nTo prove: ¬Q → ¬P\n\nProof:\nAssume ¬Q is true (for conditional proof).\nWe need to show ¬P.\n\nSuppose, for contradiction, that P is true.\nFrom P → Q (given) and P, by Modus Ponens, Q is true.\nBut we assumed ¬Q, creating a contradiction.\nTherefore P must be false, i.e., ¬P.\n\nSince assuming ¬Q led to ¬P, we have ¬Q → ¬P. QED.\n\nKey facts about contrapositive:\n- P → Q is logically equivalent to ¬Q → ¬P\n- They always have the same truth value\n- This is why Modus Tollens works: it's just Modus Ponens on the contrapositive\n- A statement and its contrapositive are proved or disproved together"},

    {"instruction": "What is a syllogism? Explain categorical syllogism with the classic example.",
     "input": "", "output": "A syllogism is a logical argument with two premises and a conclusion.\n\nCategorical Syllogism (Aristotle's classic):\n\nPremise 1 (Major): All humans are mortal. (All M are P)\nPremise 2 (Minor): Socrates is human. (All S are M)\nConclusion: Socrates is mortal. (All S are P)\n\nStructure:\n- Major term (P): mortal (predicate of conclusion)\n- Minor term (S): Socrates (subject of conclusion)\n- Middle term (M): human (appears in both premises, not in conclusion)\n\nThe middle term connects the two premises. If the connection is valid, the conclusion follows.\n\nValid forms include Barbara, Celarent, Darii, Ferio (mnemonic from medieval logicians).\nThis example is 'Darii': All M are P, S is M, therefore S is P.\n\nInvalid syllogism example:\nAll cats are animals. All dogs are animals. Therefore all cats are dogs. ← The middle term 'animals' isn't distributed properly."},

    {"instruction": "Use De Morgan's Laws to simplify: not (A and B) and not (C or D)",
     "input": "", "output": "De Morgan's Laws:\n1. ¬(A ∧ B) = ¬A ∨ ¬B (NOT of AND becomes OR of NOTs)\n2. ¬(A ∨ B) = ¬A ∧ ¬B (NOT of OR becomes AND of NOTs)\n\nApplying to: ¬(A ∧ B) ∧ ¬(C ∨ D)\n\nStep 1: Apply De Morgan's to ¬(A ∧ B):\n¬(A ∧ B) = ¬A ∨ ¬B\n\nStep 2: Apply De Morgan's to ¬(C ∨ D):\n¬(C ∨ D) = ¬C ∧ ¬D\n\nStep 3: Combine:\n(¬A ∨ ¬B) ∧ (¬C ∧ ¬D)\n\nThis cannot be simplified further without additional information about A, B, C, D.\n\nKey insight: De Morgan's Laws let you push negation inward, flipping AND↔OR. This is essential for circuit design, SQL queries, and logical proofs."},

    {"instruction": "Prove using formal logic: If A implies B, and B implies C, and A is true, then C is true.",
     "input": "", "output": "Proof using Hypothetical Syllogism and Modus Ponens:\n\nGiven:\n1. A → B (Premise)\n2. B → C (Premise)\n3. A (Premise)\n\nTo prove: C\n\nMethod 1 (Direct):\nStep 1: From premises 1 and 2, by Hypothetical Syllogism: A → C\nStep 2: From A → C and premise 3 (A), by Modus Ponens: C\n\nMethod 2 (Step by step):\nStep 1: From A → B and A, by Modus Ponens: B\nStep 2: From B → C and B, by Modus Ponens: C\n\nBoth methods are valid. Method 2 is more granular. QED.\n\nThis demonstrates the chain rule of implication: implications can be chained together, and if the first antecedent is true, the final consequent must be true."},

    {"instruction": "What is the difference between necessary and sufficient conditions? Give examples.",
     "input": "", "output": "Necessary vs Sufficient Conditions:\n\nSufficient condition: If A is true, then B must be true. (A → B)\nA is sufficient for B, but B might be true for other reasons too.\nExample: 'Being a square' is sufficient for 'being a rectangle.' Every square is a rectangle.\n\nNecessary condition: If B is true, then A must be true. (B → A, or equivalently ¬A → ¬B)\nA is necessary for B, meaning B cannot happen without A.\nExample: 'Being a rectangle' is necessary for 'being a square.' You can't be a square without being a rectangle.\n\nKey relationships:\n- If A → B: A is sufficient for B, B is necessary for A\n- If A ↔ B: A is both necessary and sufficient for B (if and only if)\n\nCommon mistake: Confusing necessary with sufficient.\n'Oxygen is necessary for fire' ✓ (no fire without oxygen)\n'Oxygen is sufficient for fire' ✗ (you also need fuel and heat)"},

    {"instruction": "Is this argument valid? 'If the code compiles, it has no syntax errors. The code has no syntax errors. Therefore, the code compiles.' Explain.",
     "input": "", "output": "This argument is INVALID. It commits the fallacy of Affirming the Consequent.\n\nLet C = 'code compiles', S = 'no syntax errors'\n\nPremise 1: C → S (If compiles, then no syntax errors)\nPremise 2: S (No syntax errors)\nConclusion: C (Code compiles) ← INVALID\n\nWhy: Having no syntax errors is NECESSARY for compilation, but not SUFFICIENT. The code might have no syntax errors but still fail to compile due to:\n- Linker errors\n- Missing dependencies\n- Type errors in some languages\n- Circular dependencies\n\nThe VALID form would be Modus Ponens:\nIf the code compiles, it has no syntax errors. The code compiles. → It has no syntax errors. ✓\n\nOr Modus Tollens:\nIf the code compiles, it has no syntax errors. It has syntax errors. → It doesn't compile. ✓"},

    {"instruction": "What is proof by contrapositive? Prove: If n² is odd, then n is odd.",
     "input": "", "output": "Proof by Contrapositive:\n\nTo prove P → Q, we instead prove ¬Q → ¬P (the contrapositive), which is logically equivalent.\n\nStatement: If n² is odd, then n is odd.\nContrapositive: If n is NOT odd (i.e., n is even), then n² is NOT odd (i.e., n² is even).\n\nProof of contrapositive:\nAssume n is even.\nThen n = 2k for some integer k.\nn² = (2k)² = 4k² = 2(2k²)\nSince 2k² is an integer, n² = 2 × (integer), so n² is even.\n\nSince the contrapositive is true, the original statement is also true. QED.\n\nWhy use contrapositive? Sometimes proving 'if not Q then not P' is easier than proving 'if P then Q' directly. In this case, working with 'n is even' is more concrete than working with 'n² is odd.'"},
]

GRAPH_PRESERVE_DATA = [
    {"instruction": "Write Dijkstra's algorithm in Python. Explain why it needs a priority queue and finds the shortest path.",
     "input": "", "output": "import heapq\ndef dijkstra(graph, start):\n    dist = {node: float('inf') for node in graph}\n    dist[start] = 0\n    pq = [(0, start)]\n    while pq:\n        d, u = heapq.heappop(pq)\n        if d > dist[u]:\n            continue\n        for v, w in graph[u]:\n            new_dist = dist[u] + w\n            if new_dist < dist[v]:\n                dist[v] = new_dist\n                heapq.heappush(pq, (new_dist, v))\n    return dist\n\nWhy priority queue?\nDijkstra always processes the node with the smallest known distance first. A priority queue (min-heap) gives us O(log V) extraction of the minimum, making the overall complexity O((V+E) log V).\n\nWhy shortest path?\nDijkstra is greedy: once we pop a node from the priority queue, its distance is finalized (no shorter path can exist). This is because all edge weights are non-negative, so any alternative path through unvisited nodes would be at least as long.\n\nKey invariant: When node u is popped, dist[u] equals the shortest distance from start to u."},

    {"instruction": "Explain the difference between BFS and Dijkstra. When would you use each?",
     "input": "", "output": "BFS vs Dijkstra:\n\nBFS (Breadth-First Search):\n- For unweighted graphs (all edges have weight 1)\n- Uses a regular queue (FIFO)\n- Time: O(V + E)\n- Finds shortest path by number of edges\n\nDijkstra:\n- For weighted graphs with non-negative weights\n- Uses a priority queue (min-heap)\n- Time: O((V + E) log V)\n- Finds shortest path by total weight\n\nWhen to use BFS:\n- Maze solving (each step costs the same)\n- Social network degree of separation\n- Level-order traversal\n\nWhen to use Dijkstra:\n- Road networks (different road lengths)\n- Network routing (different link costs)\n- Any weighted shortest path problem\n\nKey insight: BFS is a special case of Dijkstra where all weights are 1. If all weights are equal, BFS is faster because it doesn't need a priority queue.\n\nNote: Neither works with negative weights. For that, use Bellman-Ford."},

    {"instruction": "What is the A* algorithm? How does it improve on Dijkstra?",
     "input": "", "output": "A* Algorithm:\n\nA* is Dijkstra with a heuristic function h(n) that estimates the distance from node n to the goal.\n\nPriority queue uses: f(n) = g(n) + h(n)\n- g(n) = actual distance from start to n (same as Dijkstra)\n- h(n) = estimated distance from n to goal (heuristic)\n- f(n) = estimated total path cost through n\n\nHow it improves on Dijkstra:\nDijkstra explores in all directions equally. A* focuses exploration toward the goal, often finding the shortest path much faster.\n\nExample: In a road map, Dijkstra explores all cities in expanding circles. A* explores cities that are roughly 'in the direction' of the destination.\n\nAdmissible heuristic requirement:\nh(n) must NEVER overestimate the true distance. If h(n) ≤ actual distance for all n, A* is guaranteed to find the shortest path.\n\nCommon heuristics:\n- Manhattan distance (grid movement)\n- Euclidean distance (straight-line)\n- Chebyshev distance (8-directional movement)\n\nTime: O((V+E) log V) worst case, but typically much faster than Dijkstra with a good heuristic."},
]

BASE_PRESERVE_DATA = [
    {"instruction": "Write a quicksort function in Python with Lomuto partition. Explain time complexity.",
     "input": "", "output": "def quicksort(arr, low=0, high=None):\n    if high is None:\n        high = len(arr) - 1\n    if low < high:\n        pivot_idx = partition(arr, low, high)\n        quicksort(arr, low, pivot_idx - 1)\n        quicksort(arr, pivot_idx + 1, high)\n\ndef partition(arr, low, high):\n    pivot = arr[high]\n    i = low - 1\n    for j in range(low, high):\n        if arr[j] <= pivot:\n            i += 1\n            arr[i], arr[j] = arr[j], arr[i]\n    arr[i + 1], arr[high] = arr[high], arr[i + 1]\n    return i + 1\n\nTime complexity:\n- Best/Average: O(n log n) — pivot roughly divides array in half each time\n- Worst: O(n²) — when array is already sorted and we always pick the last element as pivot\n\nThe Lomuto partition scheme uses the last element as pivot. For better worst-case performance, use randomized pivot selection or median-of-three."},

    {"instruction": "Explain SQL injection and how to prevent it using parameterized queries.",
     "input": "", "output": "SQL Injection is an attack where malicious SQL code is inserted into input fields to manipulate database queries.\n\nExample vulnerability:\nquery = f\"SELECT * FROM users WHERE name = '{user_input}'\"\nIf user_input = \"' OR '1'='1\", the query becomes:\nSELECT * FROM users WHERE name = '' OR '1'='1'\nThis returns ALL users, bypassing authentication.\n\nPrevention with parameterized queries (prepared statements):\nimport sqlite3\nconn = sqlite3.connect('db.sqlite')\ncursor = conn.cursor()\ncursor.execute('SELECT * FROM users WHERE name = ?', (user_input,))\n\nThe ? placeholder separates SQL logic from data. The database engine treats user_input as pure data, never as executable SQL.\n\nOther defenses:\n1. Input validation (whitelist allowed characters)\n2. Least privilege database accounts\n3. Web Application Firewalls (WAF)\n4. ORM frameworks (parameterize by default)\n\nParameterized queries are the PRIMARY defense. Everything else is supplementary."},

    {"instruction": "Implement a binary search tree with insert and search in Python.",
     "input": "", "output": "class Node:\n    def __init__(self, value):\n        self.value = value\n        self.left = None\n        self.right = None\n\nclass BST:\n    def __init__(self):\n        self.root = None\n\n    def insert(self, value):\n        if self.root is None:\n            self.root = Node(value)\n        else:\n            self._insert(self.root, value)\n\n    def _insert(self, node, value):\n        if value < node.value:\n            if node.left is None:\n                node.left = Node(value)\n            else:\n                self._insert(node.left, value)\n        elif value > node.value:\n            if node.right is None:\n                node.right = Node(value)\n            else:\n                self._insert(node.right, value)\n\n    def search(self, value):\n        return self._search(self.root, value)\n\n    def _search(self, node, value):\n        if node is None:\n            return False\n        if value == node.value:\n            return True\n        elif value < node.value:\n            return self._search(node.left, value)\n        else:\n            return self._search(node.right, value)\n\nAverage time: O(log n) for balanced trees.\nWorst case: O(n) for degenerate (linked list) trees."},

    {"instruction": "Solve the 0/1 knapsack problem using dynamic programming. Show the table construction.",
     "input": "", "output": "def knapsack(weights, values, capacity):\n    n = len(weights)\n    dp = [[0] * (capacity + 1) for _ in range(n + 1)]\n    for i in range(1, n + 1):\n        for w in range(capacity + 1):\n            if weights[i-1] <= w:\n                dp[i][w] = max(\n                    dp[i-1][w],\n                    dp[i-1][w - weights[i-1]] + values[i-1]\n                )\n            else:\n                dp[i][w] = dp[i-1][w]\n    return dp[n][capacity]\n\nDP table construction:\n- Rows: items (0 to n)\n- Columns: capacity (0 to W)\n- dp[i][w] = maximum value using first i items with capacity w\n\nRecurrence:\n- Don't take item i: dp[i-1][w]\n- Take item i: dp[i-1][w - weight[i]] + value[i]\n- dp[i][w] = max of both choices\n\nExample: weights=[2,3,4], values=[3,4,5], capacity=5\nTable:\n       0  1  2  3  4  5\n  0:   0  0  0  0  0  0\n  1:   0  0  3  3  3  3\n  2:   0  0  3  4  4  7\n  3:   0  0  3  4  5  7\n\nAnswer: 7 (take items 1 and 2: weight=2+3=5, value=3+4=7)\n\nTime: O(n × W), Space: O(n × W)"},
]

all_data = DEBUG_DATA + LOGIC2_DATA + GRAPH_PRESERVE_DATA + BASE_PRESERVE_DATA

for name, data in [("debug_rescue_20", DEBUG_DATA), ("logic2_rescue_15", LOGIC2_DATA), 
                    ("graph_preserve_3", GRAPH_PRESERVE_DATA), ("base_preserve_4", BASE_PRESERVE_DATA)]:
    path = os.path.join(OUT, f"cezanne_{name}.json")
    with open(path, "w", encoding="utf-8") as f:
        json.dump(data, f, ensure_ascii=False, indent=2)
    print(f"  {name}: {len(data)}条 → {path}")

merged_path = os.path.join(OUT, "cezanne_rescue_v2.json")
with open(merged_path, "w", encoding="utf-8") as f:
    json.dump(all_data, f, ensure_ascii=False, indent=2)
print(f"\n  合计: {len(all_data)}条 → {merged_path}")
print(f"  debug={len(DEBUG_DATA)} logic2={len(LOGIC2_DATA)} graph={len(GRAPH_PRESERVE_DATA)} base_preserve={len(BASE_PRESERVE_DATA)}")
