import json

S1_MATH = [
    {"text": "Q: What is the derivative of f(x) = x^3 * sin(x)? A: Using the product rule: f'(x) = 3x^2 * sin(x) + x^3 * cos(x). The product rule states that d/dx[u*v] = u'*v + u*v'. Here u = x^3, v = sin(x), so u' = 3x^2, v' = cos(x)."},
    {"text": "Q: Find the eigenvalues of matrix A = [[2,1],[1,2]]. A: det(A - λI) = (2-λ)^2 - 1 = λ^2 - 4λ + 3 = (λ-1)(λ-3) = 0. Eigenvalues: λ1 = 1, λ2 = 3. For λ=1: eigenvector [1,-1]. For λ=3: eigenvector [1,1]."},
    {"text": "Q: Does the series Σ(n=1 to ∞) 1/n^2 converge? A: Yes. This is a p-series with p=2 > 1, so it converges by the p-series test. Its sum is π^2/6 (Basel problem, proved by Euler). Compare with the harmonic series Σ 1/n which diverges (p=1)."},
    {"text": "Q: State and explain the Fundamental Theorem of Calculus. A: Part 1: If F(x) = ∫[a,x] f(t)dt, then F'(x) = f(x). Part 2: ∫[a,b] f(x)dx = F(b) - F(a), where F is any antiderivative of f. This connects differentiation and integration as inverse operations."},
    {"text": "Q: In a normal distribution N(μ,σ^2), what percentage of data falls within 1, 2, and 3 standard deviations? A: 68-95-99.7 rule: ~68% within μ±σ, ~95% within μ±2σ, ~99.7% within μ±3σ. This follows from integrating the Gaussian PDF."},
    {"text": "Q: Solve the system: 2x + y = 5, x - 3y = -8. A: From equation 2: x = 3y - 8. Substitute into equation 1: 2(3y-8) + y = 5 → 7y = 21 → y = 3. Then x = 3(3) - 8 = 1. Solution: (x,y) = (1,3). Verify: 2(1)+3=5 ✓, 1-9=-8 ✓."},
    {"text": "Q: Prove by mathematical induction: 1+2+...+n = n(n+1)/2. A: Base case n=1: 1 = 1(2)/2 = 1 ✓. Inductive step: Assume true for k. Then 1+2+...+k+(k+1) = k(k+1)/2 + (k+1) = (k+1)(k/2 + 1) = (k+1)(k+2)/2. QED."},
    {"text": "Q: How many ways to arrange 5 books on a shelf? Choose 3 from 10? A: Permutations: P(5,5) = 5! = 120. Combinations: C(10,3) = 10!/(3!·7!) = 120. Key difference: permutations care about order, combinations do not."},
    {"text": "Q: What is lim(x→0) sin(x)/x? A: The limit equals 1. Proof: By the squeeze theorem, for 0 < x < π/2: cos(x) < sin(x)/x < 1. As x→0, cos(x)→1, so by squeezing sin(x)/x→1. This is fundamental for deriving all trigonometric derivatives."},
    {"text": "Q: What is a vector space? Give an example. A: A vector space V over field F is a set with operations + and · satisfying: closure, associativity, commutativity, identity (zero vector), inverses, and compatibility with scalar multiplication. Example: R^n is a vector space over R. Polynomials of degree ≤ n also form a vector space."},
    {"text": "Q: What is the Taylor series of e^x around x=0? A: e^x = Σ(n=0 to ∞) x^n/n! = 1 + x + x^2/2! + x^3/3! + ... This converges for all x ∈ R. At x=1: e = 1 + 1 + 1/2 + 1/6 + ... ≈ 2.71828."},
    {"text": "Q: Explain the Chain Rule for derivatives. A: If h(x) = f(g(x)), then h'(x) = f'(g(x)) · g'(x). Example: h(x) = sin(x^2), then h'(x) = cos(x^2) · 2x. The chain rule composes rates of change: the rate of the outer times the rate of the inner."},
    {"text": "Q: What is the determinant of a 3x3 matrix and what does it mean geometrically? A: For A = [[a,b,c],[d,e,f],[g,h,i]]: det(A) = a(ei-fh) - b(di-fg) + c(dh-eg). Geometrically, |det(A)| is the volume of the parallelepiped formed by the column vectors. det=0 means the vectors are linearly dependent (volume collapses)."},
    {"text": "Q: Explain Bayes' Theorem with an example. A: P(A|B) = P(B|A)·P(A) / P(B). Example: Disease prevalence 1%, test sensitivity 95%, specificity 90%. P(disease|positive) = 0.95·0.01 / (0.95·0.01 + 0.10·0.99) = 0.0095/0.1085 ≈ 8.8%. Even with a positive test, probability is low due to rare disease."},
    {"text": "Q: What is the difference between a convergent and divergent sequence? A: Sequence {a_n} converges to L if ∀ε>0, ∃N such that n>N → |a_n - L| < ε. Divergent sequences do not approach any limit. Examples: {1/n} → 0 (convergent), {(-1)^n} oscillates (divergent), {n} → ∞ (divergent)."},
    {"text": "Q: Explain the Mean Value Theorem. A: If f is continuous on [a,b] and differentiable on (a,b), then ∃c ∈ (a,b) such that f'(c) = (f(b)-f(a))/(b-a). Geometrically: there exists a point where the tangent is parallel to the secant line. Application: if f'=0 everywhere, then f is constant."},
    {"text": "Q: What is a linear transformation? A: A function T: V→W between vector spaces is linear if T(u+v) = T(u)+T(v) and T(cu) = cT(u) for all u,v ∈ V and scalar c. Every linear transformation from R^n to R^m can be represented by an m×n matrix. Example: rotation by angle θ is represented by [[cosθ,-sinθ],[sinθ,cosθ]]."},
    {"text": "Q: Explain integration by parts. A: ∫u dv = uv - ∫v du. Choose u and dv from the integrand, then compute du and v. LIATE rule for choosing u: Logarithmic, Inverse trig, Algebraic, Trig, Exponential. Example: ∫x·e^x dx, let u=x, dv=e^x dx → = x·e^x - ∫e^x dx = x·e^x - e^x + C."},
    {"text": "Q: What are the properties of the dot product and cross product? A: Dot product: a·b = |a||b|cosθ, commutative, measures projection. Cross product: a×b = |a||b|sinθ·n̂, anti-commutative (a×b = -(b×a)), produces vector perpendicular to both. |a×b| = area of parallelogram formed by a and b."},
    {"text": "Q: Explain the concept of a limit rigorously (ε-δ definition). A: lim(x→a) f(x) = L means: for every ε>0, there exists δ>0 such that if 0<|x-a|<δ, then |f(x)-L|<ε. The ε is the tolerance for f(x), δ is the tolerance for x. We must find δ for any given ε."},
    {"text": "Q: What is the difference between pointwise and uniform convergence? A: f_n→f pointwise: for each x, for every ε>0, ∃N(x,ε) such that n>N → |f_n(x)-f(x)|<ε. Uniform: ∃N(ε) working for ALL x simultaneously. Uniform convergence preserves continuity; pointwise does not. Example: f_n(x)=x^n on [0,1] converges pointwise but NOT uniformly."},
    {"text": "Q: Explain the Rank-Nullity Theorem. A: For linear map T: V→W, dim(V) = rank(T) + nullity(T). rank(T) = dim(image of T), nullity(T) = dim(kernel of T). Example: If A is 3×4 matrix with rank 2, then nullity = 4-2 = 2, meaning the solution space of Ax=0 is 2-dimensional."},
    {"text": "Q: What is a Cauchy sequence? Relation to completeness? A: {a_n} is Cauchy if ∀ε>0, ∃N such that m,n>N → |a_m - a_n|<ε. Every convergent sequence is Cauchy, but not every Cauchy sequence converges (e.g., in Q, sequence approaching √2 is Cauchy but has no limit in Q). R is complete: every Cauchy sequence in R converges."},
    {"text": "Q: Explain the Intermediate Value Theorem. A: If f is continuous on [a,b] and k is between f(a) and f(b), then ∃c ∈ (a,b) such that f(c)=k. Application: proving roots exist. If f(a)<0 and f(b)>0, then f has a root in (a,b). This fails for discontinuous functions."},
    {"text": "Q: What is a metric space? A: A set X with distance function d: X×X→R satisfying: (1) d(x,y)≥0, d(x,y)=0 iff x=y, (2) d(x,y)=d(y,x), (3) d(x,z)≤d(x,y)+d(y,z) (triangle inequality). Examples: R^n with Euclidean distance, function spaces with sup-norm, discrete metric d(x,y)=1 if x≠y."},
    {"text": "Q: Explain partial derivatives and the gradient. A: For f(x,y), ∂f/∂x = lim(h→0) [f(x+h,y)-f(x,y)]/h (differentiate w.r.t. x, hold y constant). Gradient ∇f = (∂f/∂x, ∂f/∂y) points in direction of steepest ascent. |∇f| gives the rate of increase. At a local extremum, ∇f = 0."},
    {"text": "Q: What is the difference between countable and uncountable sets? A: Countable: can be put in 1-1 correspondence with N (or a subset). Examples: N, Z, Q are countable. Uncountable: cannot. R is uncountable (Cantor's diagonal argument). The power set of N is uncountable. Countable unions of countable sets are countable."},
    {"text": "Q: Explain the Second Derivative Test. A: For f(x,y) with ∇f(a,b)=0: let D = f_xx·f_yy - (f_xy)^2. If D>0 and f_xx>0: local minimum. If D>0 and f_xx<0: local maximum. If D<0: saddle point. If D=0: test is inconclusive. D is the determinant of the Hessian matrix."},
    {"text": "Q: What is the relationship between derivatives and integrals? A: The Fundamental Theorem of Calculus: differentiation and integration are inverse operations. If F'(x) = f(x), then ∫[a,b] f(x)dx = F(b)-F(a). Conversely, d/dx[∫[a,x] f(t)dt] = f(x). This is the deepest connection in calculus."},
    {"text": "Q: Explain the concept of a group in abstract algebra. A: A group (G,·) is a set with binary operation satisfying: (1) Closure: a·b ∈ G, (2) Associativity: (a·b)·c = a·(b·c), (3) Identity: ∃e such that e·a = a·e = a, (4) Inverse: ∀a, ∃a^(-1) such that a·a^(-1) = e. Example: (Z,+) is a group, (Z,×) is not (no multiplicative inverse for 2)."},
]

out = {"data": [{"text": t["text"], "level": "1a"} for t in S1_MATH]}
with open(r"d:\VORTEX_FLAME\soul_training_data\cezanne\cezanne_s1_math_v2.json", "w", encoding="utf-8") as f:
    json.dump(out, f, ensure_ascii=False, indent=2)
print(f"S1: {len(S1_MATH)} items saved")
